"""Device management domain types.

Package structure mirrors the original domain/model/device*.py files,
consolidated under the canonical api/domain/device_manage/ path.
"""

from ._command_result import CommandResult
from ._credentials import (
    ArcaCredentials,
    DockerCredentials,
    K8sCredentials,
    LocalCredentials,
    PaasCredentials,
    PoolabCredentials,
    SigmaCredentials,
    TeClawCredentials,
)
from ._deploy_config import (
    ArcaDeployConfig,
    DeployConfig,
    DeviceCredentials,
    LocalDeployConfig,
    MountPermission,
    SigmaDeployConfig,
)
from ._device import (
    DestroyDeviceResponse,
    DeviceConfig,
    DeviceCreate,
    DeviceInfo,
    DeviceListResponse,
    DeviceNotFoundError,
    DeviceResponse,
    DeviceStatus,
)
from ._device_config import (
    ArcaCreateConfig,
    DeviceCreateConfig,
    DeviceCreateConfigUnion,
    DockerCreateConfig,
    K8sCreateConfig,
    LocalCreateConfig,
    PoolabCreateConfig,
    SigmaCreateConfig,
    TeClawCreateConfig,
)
from ._device_creation_result import (
    ArcaCreationResult,
    DeviceCreationResult,
    DockerCreationResult,
    K8sCreationResult,
    LocalCreationResult,
    PoolabCreationResult,
    SigmaCreationResult,
    TeClawCreationResult,
)
from ._device_facade_config import (
    ArcaDeviceConfig,
    BaseDeviceConfig,
    DockerDeviceConfig,
    K8sDeviceConfig,
    LocalDeviceConfig,
    PoolabDeviceConfig,
    SigmaDeviceConfig,
    TeClawDeviceConfig,
)
from ._device_info import (
    ArcaDeviceInfo,
    DockerDeviceInfo,
    K8sDeviceInfo,
    LocalDeviceInfo,
    PodInfo,
    PoolabDeviceInfo,
    SigmaDeviceInfo,
    TeClawDeviceInfo,
)
from ._encryptable_header_rule import (
    EncryptableHeaderRule,
    EncryptableOutBoundRule,
)
from ._errors import (
    DEVICE_CREATION_ERROR_TO_HTTP_STATUS,
    DeviceCreationError,
    DeviceFacadeException,
    DeviceNotActiveException,
    DeviceNotFoundException,
    ErrorCode,
    PaasError,
)
from ._instance_list import PoolabInstanceSummary
from ._local_device_id import InvalidLocalDeviceIdError, LocalDeviceId
from ._models import (
    MountPoint,
    OutBoundOperationRuleUpdatedMode,
    ResourceSpecification,
    Storage,
)
from ._outbound_proxy_rule import K8sOutboundProxyRule
from ._outbound_rule import HeaderOperationRule, OutBoundOperationRule
from ._protocols import DeviceService, LocalPaasService, PaasServiceFacade
from ._proxy import ProxyExecRequest, ProxyHealthRequest

__all__ = [
    "ArcaCreateConfig",
    "ArcaCreationResult",
    "ArcaCredentials",
    "ArcaDeployConfig",
    "ArcaDeviceConfig",
    "ArcaDeviceInfo",
    "BaseDeviceConfig",
    "CommandResult",
    "DeployConfig",
    "DestroyDeviceResponse",
    "DockerCreateConfig",
    "DockerCreationResult",
    "DockerCredentials",
    "DockerDeviceConfig",
    "DockerDeviceInfo",
    "DeviceConfig",
    "DeviceCreate",
    "DeviceCreateConfig",
    "DeviceCreateConfigUnion",
    "DeviceCreationResult",
    "DeviceCredentials",
    "DeviceInfo",
    "DeviceListResponse",
    "DeviceNotFoundError",
    "DeviceResponse",
    "DeviceService",
    "LocalPaasService",
    "PaasServiceFacade",
    "DeviceStatus",
    "DEVICE_CREATION_ERROR_TO_HTTP_STATUS",
    "DeviceCreationError",
    "DeviceFacadeException",
    "DeviceNotActiveException",
    "DeviceNotFoundException",
    "EncryptableHeaderRule",
    "HeaderOperationRule",
    "EncryptableOutBoundRule",
    "ErrorCode",
    "InvalidLocalDeviceIdError",
    "K8sCreateConfig",
    "K8sCreationResult",
    "K8sCredentials",
    "K8sDeviceConfig",
    "K8sDeviceInfo",
    "K8sOutboundProxyRule",
    "LocalCreateConfig",
    "LocalCreationResult",
    "LocalCredentials",
    "LocalDeployConfig",
    "LocalDeviceConfig",
    "LocalDeviceId",
    "LocalDeviceInfo",
    "MountPermission",
    "MountPoint",
    "OutBoundOperationRule",
    "OutBoundOperationRuleUpdatedMode",
    "ResourceSpecification",
    "Storage",
    "PaasCredentials",
    "PaasError",
    "PodInfo",
    "PoolabCreateConfig",
    "PoolabCreationResult",
    "PoolabCredentials",
    "PoolabDeviceConfig",
    "PoolabDeviceInfo",
    "PoolabInstanceSummary",
    "ProxyExecRequest",
    "ProxyHealthRequest",
    "SigmaCreateConfig",
    "SigmaCreationResult",
    "SigmaCredentials",
    "SigmaDeployConfig",
    "SigmaDeviceConfig",
    "SigmaDeviceInfo",
    "TeClawCreateConfig",
    "TeClawCreationResult",
    "TeClawCredentials",
    "TeClawDeviceConfig",
    "TeClawDeviceInfo",
]
