"""K8s device plugin Protocol — contract for K8s sandbox lifecycle."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from kubernetes.client import ApiClient

    from secbaas.api.bot_runtime import HttpConnectionInfo, WsConnectionInfo
    from secbaas.api.device_manage import K8sCredentials


class K8sClientManager(Protocol):
    """SPI for Kubernetes ApiClient lifecycle management.

    Core components (health checks, PaaS service) depend on this protocol
    rather than on a concrete implementation.  The real implementation
    lives in ``secbaas.plugins.sandbox.k8s.real._client_manager``.
    """

    def get_or_create_default_client(self) -> ApiClient:
        """Return any cached K8s ApiClient (or raise)."""
        ...

    def get_or_create_client(self, credentials: K8sCredentials) -> ApiClient:
        """Get or lazily create an ApiClient for the given kubeconfig."""
        ...

    def close(self) -> None:
        """Thread-safe close, clean up all cached clients."""
        ...


class K8sSandbox(Protocol):
    """A Kubernetes sandbox device with lifecycle operations.

    Represents a single K8s Deployment-managed Bot instance.
    All methods are synchronous (def), matching the existing ArcaSandbox
    and DesktopSandbox conventions. Callers wrap in asyncio.to_thread().
    """

    is_ready: bool
    sandbox_id: str

    def get_info(self) -> Any:
        """Get sandbox info including Deployment status, replicas, conditions.

        Returns:
            An info object with at minimum: sandbox_id, status, replicas, conditions.
            Optional fields depend on the implementation.
        """
        ...

    def exec_command(
        self,
        cmd: str,
        timeout_in_millis: int = 30000,
        envs: dict[str, str] | None = None,
    ) -> Any:
        """Execute a command on the sandbox Pod via exec.

        Args:
            cmd: Command string to execute.
            timeout_in_millis: Maximum execution time in milliseconds.
            envs: Environment variables for the command context.

        Returns:
            An object with at minimum: exit_code, stdout, stderr, elapsed_time.
        """
        ...

    def destroy(self) -> Any:
        """Destroy the sandbox (scale down and delete Deployment).

        Returns:
            True/False or an object indicating success.
            Idempotent: returns success if already destroyed (404 ok).
        """
        ...

    def restart(self) -> Any:
        """Restart the sandbox via rolling restart (patch Pod annotation).

        Returns:
            True/False or an object indicating success.
        """
        ...

    def update(self, **kwargs: Any) -> Any:
        """Update sandbox configuration (patch Deployment spec).

        Args:
            **kwargs: Configuration fields to update (resource limits, env vars, image).

        Returns:
            True/False or an object indicating success.
        """
        ...


class K8sSandboxPlugin(Protocol):
    """Factory protocol for creating and connecting to K8s sandbox devices.

    Abstracts the K8s SDK layer (ApiClient, CoreV1Api, AppsV1Api)
    so that K8sPaasService can operate without a direct SDK dependency.

    Implementations:
    - RealK8sSandboxPlugin: wraps the official kubernetes SDK
    - StubK8sSandboxPlugin: in-memory mock for unit tests

    Note:
        This is a SYNC factory (mirroring Arca SDK's sync API convention).
        Callers wrap calls in asyncio.to_thread() for async usage.
    """

    def create_device(
        self,
        template_id: int,
        template_uuid: str,
        tenant_name: str,
        namespace: str,
        image: str,
        cpu_request: str,
        cpu_limit: str,
        memory_request: str,
        memory_limit: str,
        envs: dict[str, str] | None = None,
        metadata: dict[str, str] | None = None,
        timeout_in_millis: int = 120000,
        envoy_yaml: str | None = None,
    ) -> K8sSandbox:
        """Create a new K8s sandbox (Deployment) and wait for it to be ready.

        Args:
            template_id: BaaS template ID.
            template_uuid: Device template UUID.
            tenant_name: Parent tenant name.
            namespace: K8s namespace for StatefulSet.
            image: Container image for Bot runtime.
            cpu_request: CPU request.
            cpu_limit: CPU limit.
            memory_request: Memory request.
            memory_limit: Memory limit.
            envs: Environment variables for the container.
            metadata: Passthrough labels/annotations.
            timeout_in_millis: Maximum creation wait time in milliseconds.
            envoy_yaml: Pre-generated Envoy YAML config (generated by
                K8sPaasService). When non-empty, plugin injects Envoy sidecar
                and proxy ConfigMap. When None/empty, no sidecar (zero-overhead).

        Returns:
            A K8sSandbox ready for use.

        Raises:
            RuntimeError: On creation failure or timeout.
        """
        ...

    def connect_device(
        self,
        sandbox_id: str,
        namespace: str,
    ) -> K8sSandbox:
        """Connect to an existing K8s sandbox by ID (idempotent query).

        Unlike Arca's connect_sync_sandbox() which actively reconnects,
        this method degrades to an idempotent existence query for K8s.

        Args:
            sandbox_id: The sandbox ID (StatefulSet Pod name in format {statefulset_name}-{ordinal}).
            namespace: K8s namespace.

        Returns:
            A K8sSandbox for the existing sandbox.

        Raises:
            RuntimeError: If the sandbox is not found.
        """
        ...

    def list_instances(
        self,
        namespace: str,
        label_selector: str | None = None,
    ) -> list[Any]:
        """List K8s sandbox instances (Deployments) matching criteria.

        Args:
            namespace: K8s namespace to query.
            label_selector: Optional label selector string.

        Returns:
            List of Deployment summary objects.
        """
        ...

    def resolve_ws_conn_info(
        self,
        paas_device_id: str,
        port: int,
        path: str,
        namespace: str,
    ) -> WsConnectionInfo:
        """Resolve WebSocket connection info for a sandbox device.

        Queries Pod IP from K8s API in real time (no caching).

        Args:
            paas_device_id: K8s Deployment name (raw platform device ID).
            port: Target port on the device.
            path: WebSocket path (e.g., /api/openclaw/ws).
            namespace: K8s namespace.

        Returns:
            WsConnectionInfo with ws:// URL and metadata.
        """
        ...

    def resolve_invoke_http_info(
        self,
        paas_device_id: str,
        port: int,
        path: str,
        namespace: str,
    ) -> HttpConnectionInfo:
        """Resolve HTTP connection info for invoking endpoints on a device.

        Args:
            paas_device_id: K8s Deployment name (raw platform device ID).
            port: Target port on the device.
            path: HTTP path (e.g., /api/v1/health).
            namespace: K8s namespace.

        Returns:
            HttpConnectionInfo with http:// URL and metadata.
        """
        ...

    def invoke_http_in_device(
        self,
        paas_device_id: str,
        method: str,
        port: int,
        path: str,
        namespace: str,
        query_string: str | None = None,
        headers: dict[str, str] | None = None,
        body: bytes | None = None,
    ) -> dict[str, Any]:
        """Invoke HTTP request directly on a device via Pod IP.

        Args:
            paas_device_id: K8s Deployment name.
            method: HTTP method (GET, POST, PUT, DELETE, etc.).
            port: Target port on the device.
            path: Request path (e.g., /api/v1/users).
            namespace: K8s namespace.
            query_string: Optional query string.
            headers: HTTP headers dict.
            body: Raw request body bytes.

        Returns:
            Dict with keys: status_code (int), headers (dict), body (base64 str).
        """
        ...

    def close(self) -> None:
        """Release any resources held by the plugin (e.g., ApiClient connections)."""
        ...

    def update_outbound_operation_rule(
        self,
        statefulset_name: str,
        namespace: str,
        envoy_yaml: str,
    ) -> None:
        """Update the outbound proxy rules ConfigMap for a StatefulSet.

        Creates the ConfigMap if it does not exist (first call).
        Patches the existing ConfigMap on subsequent calls.
        Envoy hot-reloads via ConfigMap volume mount symlink rotation.

        Args:
            statefulset_name: K8s StatefulSet name.
            namespace: K8s namespace.
            envoy_yaml: Complete Envoy configuration YAML string.

        Raises:
            RuntimeError: On API failure (404, 409, etc.).
        """
