[package]
name = "bcs-authorization"
description = "Authorization core services for BCS"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
bcs-service-api = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
bcs-authorization-store = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
