"""Start hook dispatch for device lifecycle.

Executes after_create_cmd_hook in a background thread using a wrapper script.
The wrapper script (executed via nohup) runs the hook, collects results,
and sends HTTP callback to drive device state transition.

exit_code=0 means the hook completed successfully and callback reports SUCCESS.
exit_code!=0 means the hook failed and callback reports FAILED.
The wrapper ensures callback is always sent via trap EXIT mechanism.
"""

from __future__ import annotations

import shlex
import threading
from typing import Any

from jinja2 import Template

from secbaas.community.config import ConfigPath, get_config, get_config_by_path
from secbaas.community.core.service.paas import PaasServiceFacade
from secbaas.community.core.utils.env_utils import get_current_env
from secbaas.community.logger import get_logger

logger = get_logger("core-service")

# Callback server mapping based on environment.
# Production callback URL is read from config; non-prod environments
# fall back to the pre config value so that the callback URL is
# determined by the config overlay, not hardcoded here.
_PRODUCTION_CALLBACK_PATH = ConfigPath.SECBAAS_CALLBACK_HOST_PROD
_PRE_CALLBACK_PATH = ConfigPath.SECBAAS_CALLBACK_HOST_PRE

# Jinja2 template for the wrapper script
# NOTE: Variables are pre-escaped with shlex.quote() before rendering
WRAPPER_TEMPLATE = """#!/bin/bash
# after_creation_hook_wrapper.sh
# Generated by SecBaaS start_hook_dispatcher
# Device: {{ device_uuid }}
# Publish ID: {{ publish_id }}

set -o pipefail

LOG_FILE="/home/admin/logs/start_wrapper.log"
DEVICE_UUID={{ device_uuid }}
PUBLISH_ID={{ publish_id }}
TENANT="{{ tenant }}"
CALLBACK_URL="{{ callback_server }}/api/v1/publish/device-callback?tenant={{ tenant }}"

# Logging functions
timestamp() { date -Iseconds; }
log_info() { echo "[$(timestamp)] [INFO] [$DEVICE_UUID] $*" >> "$LOG_FILE"; }
log_error() { echo "[$(timestamp)] [ERROR] [$DEVICE_UUID] $*" >> "$LOG_FILE"; }

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || LOG_FILE="/tmp/start_wrapper_$$.log"

# Export device info for Python JSON builder
export _HOOK_DEVICE_UUID="$DEVICE_UUID"
export _HOOK_PUBLISH_ID="$PUBLISH_ID"
export _HOOK_TENANT="$TENANT"

log_info "Wrapper started, publish_id=$PUBLISH_ID"

# Write hook script to file (safer than eval)
HOOK_SCRIPT_FILE=$(mktemp)
cat > "$HOOK_SCRIPT_FILE" << 'HOOK_SCRIPT_EOF'
{{ rendered_hook }}
HOOK_SCRIPT_EOF

HOOK_SCRIPT_SIZE=$(wc -c < "$HOOK_SCRIPT_FILE")
log_info "Hook script written to $HOOK_SCRIPT_FILE, size=$HOOK_SCRIPT_SIZE bytes"

# Set up temp files for output capture
HOOK_STDOUT_FILE=$(mktemp)
HOOK_STDERR_FILE=$(mktemp)
RESPONSE_FILE="/tmp/callback_resp_$$.txt"

# Cleanup function for temp files
cleanup() {
    rm -f "$HOOK_SCRIPT_FILE" "$HOOK_STDOUT_FILE" "$HOOK_STDERR_FILE" "$RESPONSE_FILE" 2>/dev/null
}

# Callback function
send_callback() {
    local retry_count=10
    local retry_delay=2

    log_info "========== CALLBACK REQUEST DETAILS =========="
    log_info "Callback URL: $CALLBACK_URL"
    log_info "Device UUID: $DEVICE_UUID"
    log_info "Publish ID: $PUBLISH_ID"
    log_info "Tenant: $TENANT"
    log_info "Hook Exit Code: $EXIT_CODE"

    # Determine result status
    local result_status
    if [ $EXIT_CODE -eq 0 ]; then
        result_status="SUCCESS"
        log_info "Result Status: SUCCESS"
    else
        result_status="FAILED"
        log_info "Result Status: FAILED"
    fi

    # Truncate outputs to avoid ARG_MAX limits (50KB each)
    local max_output=50000
    local stdout_truncated="${HOOK_STDOUT:0:$max_output}"
    local stderr_truncated="${HOOK_STDERR:0:$max_output}"
    log_info "Stdout length: {{ '${#' }}HOOK_STDOUT} (truncated to {{ '${#' }}stdout_truncated})"
    log_info "Stderr length: {{ '${#' }}HOOK_STDERR} (truncated to {{ '${#' }}stderr_truncated})"

    # Log actual hook output content for debugging
    log_info "========== HOOK STDOUT CONTENT =========="
    log_info "$stdout_truncated"
    log_info "========== HOOK STDERR CONTENT =========="
    log_info "$stderr_truncated"
    log_info "========================================="

    # Build JSON payload using Python (more reliable than jq for complex strings)
    # Use environment variables to pass large text content to avoid parameter truncation
    log_info "Building JSON payload using Python 3..."

    # Export all data as env vars for Python JSON builder (preserves newlines/special chars)
    export _HOOK_RESULT_STATUS="$result_status"
    export _HOOK_EXIT_CODE="$EXIT_CODE"
    export _HOOK_STDOUT="$stdout_truncated"
    export _HOOK_STDERR="$stderr_truncated"

    local payload
    payload=$(python3 -c '
import json
import os

try:
    data = {
        "device_uuid": os.environ["_HOOK_DEVICE_UUID"],
        "publish_id": int(os.environ["_HOOK_PUBLISH_ID"]),
        "event_type": "start",
        "result_status": os.environ["_HOOK_RESULT_STATUS"],
        "exit_code": int(os.environ["_HOOK_EXIT_CODE"]),
        "stdout": os.environ.get("_HOOK_STDOUT", ""),
        "stderr": os.environ.get("_HOOK_STDERR", ""),
        "tenant": os.environ["_HOOK_TENANT"]
    }
    print(json.dumps(data, ensure_ascii=False))
except Exception as e:
    print(f"JSON build error: {e}", file=sys.stderr)
    sys.exit(1)
' 2>&1) || {
        log_error "Python JSON build failed"
        log_error "Python output: $payload"
        payload='{}'
    }

    # Unset temp env vars
    unset _HOOK_STDOUT _HOOK_STDERR

    # Log payload size and content before sending
    log_info "---------- REQUEST BODY ----------"
    log_info "Payload size: $(echo "$payload" | wc -c) bytes"
    log_info "Payload content: $payload"
    log_info "============================================="

    for i in $(seq 1 $retry_count); do
        log_info "========== ATTEMPT $i/$retry_count =========="
        log_info "Request: POST $CALLBACK_URL"
        log_info "Headers: Content-Type: application/json"

        # Create temp file for curl stderr capture
        local curl_stderr_file
        curl_stderr_file=$(mktemp)

        local http_code
        http_code=$(curl -s -w "%{http_code}" -X POST "$CALLBACK_URL" \
             --connect-timeout 10 \
             --max-time 30 \
             -H "Content-Type: application/json" \
             -d "$payload" -o "$RESPONSE_FILE" 2>"$curl_stderr_file")

        # Log response details
        log_info "Response HTTP code: $http_code"
        if [ -f "$RESPONSE_FILE" ]; then
            log_info "Response body: $(cat "$RESPONSE_FILE")"
        fi

        if [ "$http_code" = "200" ]; then
            log_info "Callback succeeded on attempt $i"
            rm -f "$curl_stderr_file" "$RESPONSE_FILE"
            log_info "========== CALLBACK COMPLETED SUCCESSFULLY =========="
            return 0
        fi

        local curl_error
        curl_error=$(cat "$curl_stderr_file")
        rm -f "$curl_stderr_file"
        log_error "Attempt $i failed: HTTP $http_code"
        log_error "Curl error: $curl_error"
        log_info "Waiting ${retry_delay}s before retry..."
        sleep $retry_delay
    done

    log_error "========== ALL CALLBACK ATTEMPTS FAILED =========="
    log_error "Total attempts: $retry_count"
    log_error "Last HTTP code: $http_code"
    log_error "Device $DEVICE_UUID will remain PENDING"
    return 1
}

# Main cleanup and callback handler - guaranteed to run via trap
cleanup_and_callback() {
    local exit_code=$?
    # Ensure EXIT_CODE is set (use captured value or default to current)
    EXIT_CODE=${EXIT_CODE:-$exit_code}
    send_callback
    cleanup
    exit $EXIT_CODE
}

# Set trap to ensure callback happens even on signal/interrupt
trap cleanup_and_callback EXIT

# Execute hook script (not eval - safer)
bash "$HOOK_SCRIPT_FILE" > >(tee "$HOOK_STDOUT_FILE") 2> >(tee "$HOOK_STDERR_FILE" >&2)
EXIT_CODE=$?

HOOK_STDOUT=$(cat "$HOOK_STDOUT_FILE")
HOOK_STDERR=$(cat "$HOOK_STDERR_FILE")

log_info "Hook completed with exit_code=$EXIT_CODE"

# Callback and cleanup will be handled by trap EXIT
"""


def _generate_wrapper_script(
    device_uuid: str,
    publish_id: int,
    rendered_hook: str,
    callback_server: str,
    tenant: str,
) -> str:
    """Generate wrapper script by rendering the Jinja2 template.

    All shell variables are pre-escaped with shlex.quote() before rendering
    to prevent shell injection attacks.

    Args:
        device_uuid: The device UUID
        publish_id: The publish ID for tracking
        rendered_hook: The actual hook script to execute
        callback_server: The callback server URL
        tenant: The tenant name

    Returns:
        The rendered wrapper script content
    """
    # Pre-escape shell variables ONLY for bash variable assignment contexts
    # Variables used in other contexts (URL, JSON) should NOT be escaped:
    # - callback_server: used in URL construction, shlex.quote() would add
    #   unwanted single quotes to the URL
    # - publish_id: passed to jq --argjson, needs to be a bare number without
    #   shell quoting
    # - tenant: used in URL query string and JSON, no shell escaping needed
    escaped_device_uuid = shlex.quote(device_uuid)
    # rendered_hook is embedded in a heredoc, so no escaping needed
    # but we ensure it doesn't contain the heredoc delimiter

    template = Template(WRAPPER_TEMPLATE)
    return template.render(
        device_uuid=escaped_device_uuid,
        publish_id=publish_id,
        rendered_hook=rendered_hook,
        callback_server=callback_server,
        tenant=tenant,
    )


def _get_callback_server() -> str:
    """Get callback server URL based on current environment.

    Returns:
        Callback server URL read from config, keyed by environment.
    """
    env = get_current_env()
    path = _PRODUCTION_CALLBACK_PATH if env == "prod" else _PRE_CALLBACK_PATH
    return get_config_by_path(get_config(), path)


async def _execute_wrapper_script_async(
    provider_device_id: str,
    wrapper_script: str,
    facade: PaasServiceFacade,
) -> dict[str, Any]:
    """Execute wrapper script via facade.execute_command (async version).

    The wrapper is written to a file and executed with nohup to ensure
    it runs asynchronously on the device.

    Args:
        provider_device_id: The PaaS device ID
        wrapper_script: The wrapper script content to execute
        facade: PaasServiceFacade instance

    Returns:
        Dict with exit_code, stdout, stderr from the dispatch command
    """

    # Save wrapper script to /tmp for debugging (developer helper)
    debug_path = "/tmp/start_wrapper_debug.sh"
    try:
        with open(debug_path, "w") as f:  # noqa: ASYNC230
            f.write(wrapper_script)
        logger.info(f"Wrapper script saved to {debug_path} for debugging")
    except OSError as e:
        logger.warning(f"Failed to save wrapper script to {debug_path}: {e}")

    # Command to write wrapper via heredoc (avoids base64 encoding issues)
    # Using $$ for unique temp file per process
    cmd = f"""cat > /tmp/start_wrapper_$$.sh << 'WRAPPER_EOF'
{wrapper_script}
WRAPPER_EOF
chmod +x /tmp/start_wrapper_$$.sh
nohup bash /tmp/start_wrapper_$$.sh > /dev/null 2>&1 &
echo "DISPATCHED:$!"
"""
    # Note: This is a shell injection risk if wrapper_script is malicious
    # But wrapper_script is generated by our code, not from external input

    # Short timeout - we just need to dispatch, wrapper runs independently
    result = await facade.execute_command(
        paas_device_id=provider_device_id,
        cmd=cmd,
        env=None,
        timeout_seconds=30,
    )

    return {
        "exit_code": result.exit_code,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


def _execute_wrapper_script(
    provider_device_id: str,
    wrapper_script: str,
    facade: PaasServiceFacade,
) -> dict[str, Any]:
    """Execute wrapper script via facade.execute_command (sync wrapper).

    Synchronous wrapper that runs the async implementation in a new event loop.
    Used for backward compatibility with existing threaded callers.

    Args:
        provider_device_id: The PaaS device ID
        wrapper_script: The wrapper script content to execute
        facade: PaasServiceFacade instance

    Returns:
        Dict with exit_code, stdout, stderr from the dispatch command
    """
    import asyncio

    return asyncio.run(
        _execute_wrapper_script_async(provider_device_id, wrapper_script, facade=facade)
    )


def dispatch_start_hook(
    tenant: str,
    device_uuid: str,
    provider_device_id: str,
    rendered_hook: str,
    hook_timeout: int,  # noqa: ARG001 - kept for API compatibility
    facade: PaasServiceFacade,
    publish_id: int | None = None,
) -> None:
    """Dispatch after_create_cmd_hook using wrapper script.

    The wrapper script is executed on the device via nohup. It:
    1. Executes the actual hook script
    2. Collects exit_code, stdout, stderr
    3. Sends HTTP callback with results (10 retries)
    4. Handles all state transition logic via callback

    This function only handles wrapper dispatch failures. All hook
    execution results are reported via the HTTP callback mechanism.

    Args:
        tenant: The tenant name
        device_uuid: The device UUID
        provider_device_id: The PaaS device ID
        rendered_hook: The hook script content (already rendered)
        hook_timeout: Timeout for hook execution (unused, kept for compatibility)
        publish_id: Optional publish ID for tracking
        facade: PaasServiceFacade instance
    """

    def _run_hook() -> None:
        """Generate and execute wrapper script."""
        try:
            # Get callback server based on environment
            callback_server = _get_callback_server()

            # Generate wrapper script
            wrapper_script = _generate_wrapper_script(
                device_uuid=device_uuid,
                publish_id=publish_id or 0,
                rendered_hook=rendered_hook,
                callback_server=callback_server,
                tenant=tenant,
            )

            logger.info(
                f"Generated wrapper script for {device_uuid} "
                f"(callback_server={callback_server})"
            )

            # Execute wrapper script (dispatches nohup process on device)
            result = _execute_wrapper_script(
                provider_device_id, wrapper_script, facade=facade
            )

            exit_code = result["exit_code"]
            stdout = result["stdout"]
            stderr = result["stderr"]

            if exit_code != 0:
                # Wrapper failed to dispatch — report failure
                logger.error(
                    f"Wrapper dispatch FAILED for {device_uuid}: "
                    f"exit_code={exit_code}, stderr={stderr[:200]}"
                )
                _report_failure(
                    device_uuid=device_uuid,
                    publish_id=publish_id,
                    exit_code=exit_code,
                    stdout=stdout,
                    stderr=stderr,
                    tenant=tenant,
                )
            else:
                # Wrapper dispatched successfully
                # The wrapper will send callback with hook results
                logger.info(
                    f"Wrapper dispatched for {device_uuid}: "
                    f"stdout={stdout[:100]}, wrapper will send callback"
                )

        except Exception as e:
            # Unexpected exception during dispatch
            logger.error(f"Wrapper dispatch exception for {device_uuid}: {e}")
            _report_failure(
                device_uuid=device_uuid,
                publish_id=publish_id,
                exit_code=None,
                stdout=None,
                stderr=str(e),
                tenant=tenant,
            )

    thread = threading.Thread(
        target=_run_hook,
        daemon=True,
        name=f"hook-{device_uuid[:8]}",
    )
    thread.start()
    logger.info(f"Start hook thread started for device {device_uuid}")


def _report_failure(
    device_uuid: str,
    publish_id: int | None,
    exit_code: int | None,
    stdout: str | None,
    stderr: str | None,
    tenant: str,
) -> None:
    """Report hook launch failure via internal callback.

    Only called when the wrapper script fails to dispatch (non-zero exit or
    exception). For successful dispatch, the wrapper sends the callback.

    Args:
        device_uuid: The device UUID
        publish_id: Optional publish ID
        exit_code: Exit code from failed dispatch
        stdout: stdout from failed dispatch
        stderr: stderr from failed dispatch
        tenant: The tenant name
    """
    import asyncio

    try:
        from secbaas.community.api.publish_manage import DeviceCallbackRequest

        async def send_callback() -> Any:
            callback = DeviceCallbackRequest(
                device_uuid=device_uuid,
                publish_id=publish_id or 0,
                event_type="start",
                result_status="FAILED",
                exit_code=exit_code,
                stdout=stdout,
                stderr=stderr,
                tenant=tenant,
            )
            from secbaas.community.core.utils.callback_utils import (
                handle_device_callback,
            )

            return await handle_device_callback(callback)

        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            # No running loop - use asyncio.run
            result = asyncio.run(send_callback())
        else:
            # Running loop present in current thread - schedule coroutine safely
            future = asyncio.run_coroutine_threadsafe(send_callback(), loop)
            result = future.result(timeout=30)

        logger.info(f"Failure callback result for {device_uuid}: {result}")
    except Exception as e:
        logger.error(
            f"Failed to report failure callback for {device_uuid}: {e}",
            exc_info=True,
        )
