[package]
name = "bcs-human-notify-dummy"
description = "Dummy human mention notification backend for BCS (logs only)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bcs-config-api = { workspace = true }
bcs-human-notify-api = { workspace = true }
futures = { workspace = true }
inventory = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bcs-test-support = { workspace = true }
tokio = { workspace = true }
