-- 013_permission_request_public_id.sql — external string request_id for edge-permission requests.
-- Spec: src/bcs/docs/superpowers/specs/2026-08-18-friend-edge-permission-reform.md (D11 — string
-- business ids; opaque-uuid re-key deferred). Applied externally (ops/CI); the bcs binary runs
-- only SQLite migrations (see bootstrap/bcs/src/migrations.rs step v15).
--
-- The bigint migration (011) made `permission_requests.id` (BIGINT auto-increment) the PK and
-- exposed it externally as `request_id`. That leaked auto-increment integers to clients and
-- contradicted the OpenAPI contract (`type: string`). This migration keeps `id` as the internal
-- PK/FK join key and adds a separate, client-facing `request_id` column (a bare UUID v4, simple
-- form, generated by the service via `Uuid::new_v4().simple().to_string()`). Existing rows are
-- backfilled with a bare UUID so the NOT NULL + UNIQUE constraints hold.

-- 1. Add the column with a safe default so existing rows satisfy NOT NULL.
ALTER TABLE `permission_requests`
  ADD COLUMN `request_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '外部业务 id（裸 UUID v4）；内部 bigint PK 见 id 列';

-- 2. Backfill every existing row with a fresh bare UUID (MySQL UUID() is v1; strip dashes to
--    match the 32-hex simple form the service produces via Uuid::new_v4().simple()).
UPDATE `permission_requests`
   SET `request_id` = REPLACE(UUID(), '-', '')
 WHERE `request_id` = '';

-- 3. Enforce global uniqueness of the external id (uuid-backed, so collision-free; the unique
--    index also lets approve/reject/cancel lookups by `request_id` stay O(log n)).
CREATE UNIQUE INDEX `uk_permission_requests_request_id`
    ON `permission_requests` (`request_id`);

-- 4. Idempotency note: the `(env, from_id, to_id, request_kind, status)` idempotency select in
--    the store is unchanged; `request_id` is generated per-insert and is not part of the
--    dedup key.
