-- Managed message deliveries. Deploy before enabling any queue flow.
CREATE TABLE IF NOT EXISTS bcs_message_deliveries (
    delivery_id VARCHAR(128) NOT NULL,
    env VARCHAR(64) NOT NULL,
    source_message_id VARCHAR(128) NOT NULL,
    target_bot_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(512) NOT NULL,
    group_id VARCHAR(128) NOT NULL,
    source_session_seq BIGINT NOT NULL,
    flow_kind VARCHAR(32) NOT NULL,
    kind VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    state_version BIGINT NOT NULL,
    may_have_been_sent BOOLEAN NOT NULL,
    wait_reason VARCHAR(32),
    available_at_ms BIGINT NOT NULL,
    expire_at_ms BIGINT,
    created_at_ms BIGINT NOT NULL,
    updated_at_ms BIGINT NOT NULL,
    run_id VARCHAR(128),
    idempotency_key VARCHAR(128),
    attempt_no INTEGER NOT NULL,
    request_id VARCHAR(128),
    send_started_at_ms BIGINT,
    submitted_at_ms BIGINT,
    accepted_at_ms BIGINT,
    run_deadline_at_ms BIGINT,
    terminal_at_ms BIGINT,
    bound_to_delivery_id VARCHAR(128),
    cancel_requested_at_ms BIGINT,
    cancel_requested_by VARCHAR(128),
    cancel_reason TEXT,
    abort_request_id VARCHAR(128),
    abort_started_at_ms BIGINT,
    cancel_deadline_at_ms BIGINT,
    last_error_code VARCHAR(128),
    semantic_projection_json JSON NOT NULL,
    transport_context_json JSON,
    PRIMARY KEY (env, delivery_id),
    UNIQUE (env, source_message_id, target_bot_id),
    UNIQUE (env, run_id),
    UNIQUE (env, idempotency_key),
    UNIQUE (env, request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX idx_delivery_schedule ON bcs_message_deliveries (env, status, available_at_ms);
CREATE INDEX idx_delivery_lane ON bcs_message_deliveries (env, target_bot_id, session_id, source_session_seq);
CREATE INDEX idx_delivery_context ON bcs_message_deliveries (env, bound_to_delivery_id);
CREATE INDEX idx_delivery_source ON bcs_message_deliveries (env, source_message_id);
