import React from 'react';
import styled from 'styled-components';
import { assignBotAppearances } from './appearance';
import { botSprite, spriteUrl, sprites, type SpriteCoordinate } from './assets';
import { sceneSeatGeometry, type Facing, type RoomComposition } from './sceneLayout';
import { primaryOutputActor, stateLabels } from './visualState';
import { truncateBubbleText } from './layout';
import type { ActorViewModel, HostActor, PlayerActor, PlayerState } from './types';

const Room=styled.div<{ $composition:RoomComposition }>`position:relative;min-height:${p=>p.$composition==='wide'?'520px':p.$composition==='medium'?'500px':'132px'};overflow:${p=>p.$composition==='narrow'?'visible':'hidden'};border:4px solid #504768;background-color:#39324b;box-shadow:inset 0 0 0 4px #211f32,6px 6px 0 #0c0d16;`;
const Surface=styled.div`pointer-events:none;position:absolute;inset:0;`;
const Wall=styled(Surface)`height:34%;background-color:#514b61;background-image:url("${spriteUrl(sprites.wall)}");background-repeat:repeat;background-size:32px 32px;background-blend-mode:multiply;box-shadow:inset 0 -8px #201c30;opacity:.9;`;
const Floor=styled(Surface)`top:34%;background-color:#6c4b50;background-image:url("${spriteUrl(sprites.floor)}");background-repeat:repeat;background-size:48px 48px;background-blend-mode:multiply;opacity:.88;`;
const BaseSprite=styled.span<{ $sprite:SpriteCoordinate;$scale?:number }>`display:inline-block;width:${p=>p.$sprite.width*(p.$scale??1)}px;height:${p=>p.$sprite.height*(p.$scale??1)}px;background-image:url("${p=>spriteUrl(p.$sprite)}");background-size:100% 100%;background-position:center;background-repeat:no-repeat;image-rendering:pixelated;`;
const Deco=styled(BaseSprite)<{ $x:number;$y:number }>`position:absolute;left:${p=>p.$x}%;top:${p=>p.$y}%;transform:translate(-50%,-50%);`;
const Table=styled(BaseSprite)<{ $composition:RoomComposition }>`position:absolute;left:50%;top:${p=>p.$composition==='narrow'?'70%':'62%'};transform:translate(-50%,-50%);filter:drop-shadow(0 6px 0 #201c30);`;
const HostButton=styled.button`position:absolute;z-index:30;left:50%;top:8%;transform:translateX(-50%);display:flex;align-items:center;gap:8px;border:0;padding:0;color:#fff;background:transparent;font:inherit;cursor:pointer;&:focus-visible{outline:3px solid #fff;outline-offset:4px}`;
const HostPlate=styled.span`padding:5px 8px;border:2px solid #201c30;background:#a94f5c;box-shadow:3px 3px 0 #201c30;font-size:10px;`;
const ActorButton=styled.button<{ $x:number;$y:number;$depth:number;$attention:boolean;$eliminated:boolean }>`position:absolute;z-index:${p=>40+p.$depth};left:${p=>p.$x}%;top:${p=>p.$y}%;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;width:104px;border:0;padding:0;color:#fff;background:transparent;font:inherit;cursor:pointer;opacity:${p=>p.$eliminated?.62:1};${p=>p.$attention?'filter:drop-shadow(0 0 6px #f2b36c);animation:pixel-pulse 1s steps(2,end) infinite;':''}&:focus-visible{outline:3px solid #fff;outline-offset:2px}@keyframes pixel-pulse{50%{transform:translate(-50%,-53%)}}`;
const ActorStack=styled.span`position:relative;display:block;width:52px;height:64px;`;
const Portrait=styled(BaseSprite)`position:absolute;left:10px;top:4px;`;
const IdentityFrame=styled(BaseSprite)`position:absolute;left:10px;top:4px;`;
const Marker=styled(BaseSprite)`position:absolute;right:-4px;top:0;width:24px;height:24px;`;
const Plate=styled.span`max-width:104px;border:2px solid #201c30;padding:3px 5px;background:#26273c;font-size:9px;line-height:1.3;text-align:center;box-shadow:2px 2px 0 #201c30;`;
const Chair=styled(BaseSprite)<{ $facing:Facing }>`position:absolute;left:10px;top:27px;opacity:.95;`;
const ActorShadow=styled(BaseSprite)`position:absolute;left:10px;top:30px;`;
const Bubble=styled.button<{ $x:number;$y:number }>`position:absolute;z-index:180;left:${p=>p.$x}%;top:${p=>p.$y}%;transform:translate(-50%,-100%);max-width:170px;border:3px solid #201c30;padding:6px 8px;color:#201c30;background:#f9edcf;font:inherit;font-size:10px;cursor:pointer;`;
const CompactMarker=styled.button<{ $x:number;$y:number }>`position:absolute;z-index:170;left:${p=>p.$x}%;top:${p=>p.$y}%;width:25px;height:25px;border:2px solid #201c30;border-radius:0;color:#201c30;background:#f2b36c;font:inherit;cursor:pointer;`;
const Roster=styled.div`display:grid;gap:7px;margin-top:10px;`;
const RosterButton=styled.button<{ $attention:boolean }>`display:flex;align-items:center;gap:8px;width:100%;border:2px solid ${p=>p.$attention?'#f2b36c':'#504768'};padding:7px;color:#fff;background:#26273c;font:inherit;text-align:left;cursor:pointer;`;
const RosterText=styled.span`display:grid;gap:2px;font-size:10px;`;
const VignetteTitle=styled.span`position:absolute;left:12px;bottom:8px;z-index:80;padding:4px 6px;border:2px solid #201c30;background:#26273c;font-size:9px;`;

function markerFor(state:PlayerState){return state==='action_required'?sprites.action:state==='active_speech'?sprites.speaking:state==='completed_speech'?sprites.completed:state==='voted'?sprites.voted:state==='eliminated'?sprites.eliminated:state==='retrying'?sprites.retrying:state==='error'?sprites.error:undefined}
function chairSprite(facing:Facing){return facing==='front'?sprites.chairFront:facing==='rear'?sprites.chairRear:facing==='left'?sprites.chairLeft:sprites.chairRight}
export interface RoomSceneProps{composition:RoomComposition;actors:ActorViewModel[];host?:ActorViewModel;currentViewerActorId?:string;voting:boolean;showHostOutput:boolean;onOpen:(actorId:string,type:'select-actor'|'select-bubble',element:HTMLElement)=>void}
export function RoomScene({composition,actors,host,currentViewerActorId,voting,showHostOutput,onOpen}:RoomSceneProps){
 const players=actors.filter(a=>a.kind==='player');const ids=players.map(a=>a.actor.actorId);const appearances=assignBotAppearances(ids);const geometry=sceneSeatGeometry(ids,composition);const primary=primaryOutputActor(players);const room=<Room $composition={composition} aria-label="谁是卧底像素游戏房间" data-room-composition={composition}>
  <Wall data-room-layer="wall"/><Floor data-room-layer="floor"/>{composition!=='narrow'&&<><Deco $sprite={sprites.window} $x={18} $y={15}/><Deco $sprite={sprites.clock} $x={82} $y={15}/><Deco $sprite={sprites.shelf} $x={10} $y={47} $scale={2}/><Deco $sprite={sprites.plant} $x={90} $y={49} $scale={2}/><Deco $sprite={sprites.frame} $x={70} $y={16} $scale={2}/><Deco $sprite={sprites.lamp} $x={88} $y={31}/></>}
  <HostButton type="button" aria-label={`打开主持人 ${(host?.actor as HostActor|undefined)?.displayName??'主持人'} 详情`} onClick={e=>host&&onOpen(host.actor.actorId,'select-actor',e.currentTarget)}><BaseSprite $sprite={sprites.host}/><HostPlate>{host?.actor.displayName??'主持人'} · 主持中</HostPlate></HostButton>
  <Table data-room-layer="table" $composition={composition} $sprite={sprites.table} $scale={composition==='narrow'?2:4} aria-hidden="true"/>
  {composition!=='narrow'&&players.map((actor,index)=>{const p=actor.actor as PlayerActor,g=geometry[index];const human=p.isHuman||p.actorId===currentViewerActorId;const attention=actor.state==='active_speech'||actor.state==='action_required'||p.actorId===currentViewerActorId;const marker=markerFor(actor.state as PlayerState);return <React.Fragment key={p.actorId}><ActorButton data-actor-id={p.actorId} $x={g.x} $y={g.y} $depth={g.depth} $attention={attention} $eliminated={actor.state==='eliminated'} type="button" onClick={e=>onOpen(p.actorId,'select-actor',e.currentTarget)} aria-label={`打开 ${p.seatNumber}号 ${p.displayName} 详情，${stateLabels[actor.state as PlayerState]}${human?'，当前玩家':''}`}><ActorStack><Chair $sprite={chairSprite(g.facing)} $facing={g.facing}/><ActorShadow $sprite={sprites.actorShadow}/><Portrait $sprite={botSprite(appearances[p.actorId])}/>{human&&<IdentityFrame $sprite={sprites.humanFrame}/>} {marker&&<Marker $sprite={marker}/>}</ActorStack><Plate><strong>{p.seatNumber}号 · {p.displayName}{human?'（你）':''}</strong><br/>{stateLabels[actor.state as PlayerState]}</Plate></ActorButton>{actor.latestOutput&&!voting&&(p.actorId===primary?<Bubble $x={g.bubbleAnchor.x} $y={g.bubbleAnchor.y} type="button" onClick={e=>onOpen(p.actorId,'select-bubble',e.currentTarget)} aria-label={`${p.displayName} 的完整公开发言`}>{truncateBubbleText(actor.latestOutput.text,62).text}</Bubble>:<CompactMarker $x={g.x+6} $y={g.y-10} type="button" onClick={e=>onOpen(p.actorId,'select-bubble',e.currentTarget)} aria-label={`打开 ${p.displayName} 的完整公开发言`}>“<span style={{position:'absolute',width:1,height:1,overflow:'hidden',clipPath:'inset(50%)'}}>{actor.latestOutput.text}</span></CompactMarker>)}</React.Fragment>})}
  {composition==='narrow'&&<VignetteTitle>室内圆桌 · {players.find(a=>a.state==='active_speech'||a.state==='action_required')?.actor.displayName??'等待下一步'}</VignetteTitle>}
  {host?.latestOutput&&showHostOutput&&<Bubble $x={50} $y={composition==='narrow'?42:22} type="button" onClick={e=>onOpen(host.actor.actorId,'select-bubble',e.currentTarget)}>{truncateBubbleText(host.latestOutput.text,54).text}</Bubble>}
 </Room>;
 if(composition!=='narrow')return room;
 return <>{room}<Roster data-region="participant-roster">{players.map(actor=>{const p=actor.actor as PlayerActor;const human=p.isHuman||p.actorId===currentViewerActorId;const marker=markerFor(actor.state as PlayerState);return <RosterButton key={p.actorId} $attention={actor.state==='action_required'||actor.state==='active_speech'} type="button" onClick={e=>onOpen(p.actorId,'select-actor',e.currentTarget)} aria-label={`打开 ${p.seatNumber}号 ${p.displayName} 详情`}><BaseSprite $sprite={botSprite(appearances[p.actorId])}/>{marker&&<BaseSprite $sprite={marker}/>}<RosterText><strong>{p.seatNumber}号 · {p.displayName}{human?'（你）':''}</strong><span>{stateLabels[actor.state as PlayerState]}{actor.latestOutput&&!voting?` · ${truncateBubbleText(actor.latestOutput.text,38).text}`:''}</span></RosterText></RosterButton>})}</Roster></>;
}
