"""
LLM Analyzer Module for PinchBench Doctor.

Uses LLM to analyze agent thinking, query semantics, and root causes.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class LLMInsight:
    """Insight generated by LLM analysis."""
    insight_id: str
    category: str  # "cognitive_gap", "skill_confusion", "reasoning_error", "context_loss"
    severity: str  # "high", "medium", "low"
    description: str
    root_cause: str
    suggestion: str
    evidence: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0  # 0.0 - 1.0


@dataclass
class ThinkingAnalysis:
    """Analysis of agent's thinking process."""
    original_intent: str  # Agent 最初想做什么
    actual_action: str    # 实际做了什么
    gap_description: str  # 意图与行动的差距
    cognitive_bias: Optional[str] = None  # 认知偏差类型


@dataclass
class SemanticContext:
    """Semantic understanding of the task context."""
    user_intent: str           # 用户真实意图
    required_entities: List[Dict]  # 需要的实体（如知识库名、文档ID等）
    implied_workflow: List[str]    # 隐含的工具调用流程
    missing_knowledge: List[str]   # Agent 可能缺乏的知识


class LLMAnalyzer:
    """LLM-based analyzer for deep diagnosis.

    Uses OpenAI-compatible chat completions API so it can reuse the same
    ``base_url`` / ``api_key`` that the benchmark judge already has.
    """

    DEFAULT_BASE_URL = "https://api.openai.com/v1/chat/completions"

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None, base_url: Optional[str] = None):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY") or os.environ.get("JUDGE_API_KEY")
        self.model = model or os.environ.get("DOCTOR_LLM_MODEL", "claude-sonnet-4-6")
        # base_url should point to the chat completions endpoint.
        # If a generic base (e.g. "https://host/v1") is given, append the path.
        raw_base = base_url or os.environ.get("OPENAI_BASE_URL")
        if raw_base:
            self.endpoint = raw_base.rstrip("/")
            if not self.endpoint.endswith("/chat/completions"):
                self.endpoint = self.endpoint.rstrip("/") + "/chat/completions"
        else:
            self.endpoint = self.DEFAULT_BASE_URL

        if self.api_key:
            logger.info("LLM Analyzer initialized with model: %s (endpoint: %s)", self.model, self.endpoint)
        else:
            logger.info("LLM Analyzer initialized in dry-run mode (no API key)")

    def is_available(self) -> bool:
        """Check if LLM analysis is available."""
        return self.api_key is not None

    def analyze_session(
        self,
        task_id: str,
        user_query: str,
        thinking_sequence: List[Dict],
        tool_calls: List[Dict],
        issues: List[Any],
    ) -> List[LLMInsight]:
        """
        Analyze a complete session using LLM.

        Args:
            task_id: Task identifier
            user_query: Original user query
            thinking_sequence: List of thinking content with timestamps
            tool_calls: Extracted tool calls
            issues: Issues detected by rule-based detectors

        Returns:
            List of LLM-generated insights
        """
        if not self.is_available():
            logger.debug("LLM not available, skipping analysis")
            return []

        insights = []

        # 1. Analyze thinking process
        thinking_insights = self._analyze_thinking_gap(
            task_id, user_query, thinking_sequence, tool_calls
        )
        insights.extend(thinking_insights)

        # 2. Analyze semantic context
        semantic_insights = self._analyze_semantic_context(
            task_id, user_query, thinking_sequence, tool_calls, issues
        )
        insights.extend(semantic_insights)

        # 3. Analyze root cause of detected issues
        for issue in issues:
            root_cause_insight = self._analyze_issue_root_cause(
                task_id, issue, user_query, thinking_sequence
            )
            if root_cause_insight:
                insights.append(root_cause_insight)

        return insights

    def _analyze_thinking_gap(
        self,
        task_id: str,
        user_query: str,
        thinking_sequence: List[Dict],
        tool_calls: List[Dict],
    ) -> List[LLMInsight]:
        """Analyze gaps between agent's thinking and actual actions."""

        if not thinking_sequence:
            return []

        prompt = self._build_thinking_analysis_prompt(
            user_query, thinking_sequence, tool_calls
        )

        try:
            response = self._call_llm(prompt)
            analysis = self._parse_thinking_analysis(response)

            if analysis and analysis.gap_description:
                insight = LLMInsight(
                    insight_id=f"llm_thinking_{task_id[:8]}",
                    category="cognitive_gap",
                    severity="high" if analysis.cognitive_bias else "medium",
                    description=analysis.gap_description,
                    root_cause=analysis.cognitive_bias or "意图与行动不一致",
                    suggestion=self._generate_cognitive_suggestion(analysis),
                    evidence={
                        "original_intent": analysis.original_intent,
                        "actual_action": analysis.actual_action,
                        "thinking_count": len(thinking_sequence),
                    },
                    confidence=0.8,
                )
                return [insight]
        except Exception as e:
            logger.warning("Thinking analysis failed: %s", e)

        return []

    def _analyze_semantic_context(
        self,
        task_id: str,
        user_query: str,
        thinking_sequence: List[Dict],
        tool_calls: List[Dict],
        issues: List[Any],
    ) -> List[LLMInsight]:
        """Analyze semantic understanding of task context."""

        prompt = self._build_semantic_analysis_prompt(
            user_query, thinking_sequence, tool_calls, issues
        )

        try:
            response = self._call_llm(prompt)
            context = self._parse_semantic_context(response)

            insights = []

            # Check for missing entity understanding
            for entity in context.required_entities:
                if not entity.get("agent_recognized", True):
                    insight = LLMInsight(
                        insight_id=f"llm_entity_{task_id[:8]}_{entity['name']}",
                        category="context_loss",
                        severity="high",
                        description=f"Agent 未识别用户指令中的关键实体: {entity['name']}",
                        root_cause="自然语言实体识别能力不足或缺少相关示例",
                        suggestion=f"在 skill 描述中添加 '{entity['name']}' 的识别示例，说明如何从用户指令中提取该实体",
                        evidence={
                            "entity": entity,
                            "user_query": user_query,
                        },
                        confidence=0.75,
                    )
                    insights.append(insight)

            # Check for workflow understanding
            if context.implied_workflow and len(tool_calls) < len(context.implied_workflow):
                insight = LLMInsight(
                    insight_id=f"llm_workflow_{task_id[:8]}",
                    category="reasoning_error",
                    severity="medium",
                    description="Agent 未完成完整的工具调用流程",
                    root_cause="对工作流的理解不完整，可能过早终止或遗漏步骤",
                    suggestion="在 Memory 中添加该任务的完整工作流示例，明确每个步骤的必要性",
                    evidence={
                        "implied_workflow": context.implied_workflow,
                        "actual_tools": [tc["tool_name"] for tc in tool_calls],
                        "missing_knowledge": context.missing_knowledge,
                    },
                    confidence=0.7,
                )
                insights.append(insight)

            return insights
        except Exception as e:
            logger.warning("Semantic analysis failed: %s", e)

        return []

    def _analyze_issue_root_cause(
        self,
        task_id: str,
        issue: Any,
        user_query: str,
        thinking_sequence: List[Dict],
    ) -> Optional[LLMInsight]:
        """Deep analysis of a specific issue's root cause."""

        prompt = self._build_root_cause_prompt(issue, user_query, thinking_sequence)

        try:
            response = self._call_llm(prompt)
            root_cause_analysis = json.loads(response)

            return LLMInsight(
                insight_id=f"llm_root_{issue.issue_id}",
                category="skill_confusion" if "skill" in root_cause_analysis.get("cause", "") else "reasoning_error",
                severity=issue.severity.value,
                description=root_cause_analysis.get("description", issue.description),
                root_cause=root_cause_analysis.get("cause", "未知"),
                suggestion=root_cause_analysis.get("suggestion", issue.suggestion),
                evidence={
                    "original_issue": issue.pattern_id,
                    "agent_thinking": [t.get("content", "") for t in thinking_sequence[-3:]],
                },
                confidence=root_cause_analysis.get("confidence", 0.7),
            )
        except Exception as e:
            logger.warning("Root cause analysis failed for issue %s: %s", issue.issue_id, e)

        return None

    def _call_llm(self, prompt: str) -> str:
        """Call LLM via OpenAI-compatible chat completions API."""
        if not self.api_key:
            raise RuntimeError("LLM API key not available")

        from urllib import error as urlerror, request as urlrequest

        payload = json.dumps({
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.2,
            "max_tokens": 4000,
        }).encode("utf-8")

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        req = urlrequest.Request(self.endpoint, data=payload, headers=headers, method="POST")
        try:
            with urlrequest.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode("utf-8"))
        except urlerror.HTTPError as exc:
            body = ""
            try:
                body = exc.read().decode("utf-8", errors="replace")[:500]
            except Exception:
                pass
            raise RuntimeError(f"LLM API error ({exc.code}): {body}") from exc
        except urlerror.URLError as exc:
            raise RuntimeError(f"LLM network error: {exc.reason}") from exc

        choices = data.get("choices", [])
        if not choices:
            raise RuntimeError("LLM response has no choices")
        return choices[0].get("message", {}).get("content", "")

    def _build_thinking_analysis_prompt(
        self,
        user_query: str,
        thinking_sequence: List[Dict],
        tool_calls: List[Dict],
    ) -> str:
        """Build prompt for thinking gap analysis."""

        thinking_text = "\n\n".join([
            f"[{i+1}] {t.get('timestamp', 'unknown')}\n{t.get('content', '')}"
            for i, t in enumerate(thinking_sequence)
        ])

        tool_text = "\n".join([
            f"- {tc['tool_name']}: {json.dumps(tc['arguments'], ensure_ascii=False)}"
            for tc in tool_calls
        ])

        return f"""你是一个专业的 Agent 行为分析师。请分析以下 Agent 的思考过程与实际工具调用之间的差距。

## 用户指令
{user_query}

## Agent 的思考过程
{thinking_text}

## 实际调用的工具
{tool_text}

请分析并返回 JSON 格式：
{{
    "original_intent": "Agent 最初想要完成什么",
    "actual_action": "Agent 实际做了什么",
    "gap_description": "思考与行动的差距描述",
    "cognitive_bias": "认知偏差类型（如有）: premature_conclusion / context_loss / parameter_confusion / 等",
    "reason": "为什么会出现这个差距"
}}

只返回 JSON，不要其他解释。"""

    def _build_semantic_analysis_prompt(
        self,
        user_query: str,
        thinking_sequence: List[Dict],
        tool_calls: List[Dict],
        issues: List[Any],
    ) -> str:
        """Build prompt for semantic context analysis."""

        thinking_summary = thinking_sequence[0].get("content", "")[:500] if thinking_sequence else "无"

        issue_text = "\n".join([
            f"- [{i.pattern_id}] {i.description}"
            for i in issues[:3]
        ])

        return f"""你是一个专业的自然语言理解分析师。请分析用户指令中的隐含信息和 Agent 的理解差距。

## 用户指令
{user_query}

## Agent 的初步思考
{thinking_summary}

## 检测到的工具调用问题
{issue_text}

请分析并返回 JSON 格式：
{{
    "user_intent": "用户的真实意图",
    "required_entities": [
        {{
            "name": "实体名称（如知识库名、文档ID等）",
            "type": "实体类型",
            "value_in_query": "在用户指令中的值",
            "agent_recognized": true/false,
            "how_to_extract": "应该如何从指令中提取"
        }}
    ],
    "implied_workflow": ["步骤1", "步骤2", ...],
    "missing_knowledge": ["Agent 可能缺乏的知识1", "知识2"]
}}

只返回 JSON，不要其他解释。"""

    def _build_root_cause_prompt(
        self,
        issue: Any,
        user_query: str,
        thinking_sequence: List[Dict],
    ) -> str:
        """Build prompt for root cause analysis."""

        thinking_near_issue = "\n".join([
            t.get("content", "")[:300]
            for t in thinking_sequence[-2:]
        ])

        return f"""你是一个专业的 Agent 错误诊断专家。请深入分析以下问题的根本原因。

## 用户指令
{user_query}

## Agent 的相关思考
{thinking_near_issue}

## 检测到的问题
- 类型: {issue.pattern_id} ({issue.pattern_name})
- 描述: {issue.description}
- 涉及工具: {issue.tool_name or 'N/A'}
- 证据: {json.dumps(issue.evidence, ensure_ascii=False, indent=2)[:500]}

请深入分析并返回 JSON 格式：
{{
    "description": "问题的更精确描述",
    "cause": "根本原因分析",
    "is_skill_issue": true/false,
    "is_reasoning_issue": true/false,
    "suggestion": "具体的修复建议",
    "confidence": 0.85
}}

分析维度：
1. 是 Skill 描述不清导致的？
2. 是 Agent 推理错误导致的？
3. 是缺少必要 Memory 导致的？
4. 其他原因？

只返回 JSON，不要其他解释。"""

    def _parse_thinking_analysis(self, response: str) -> Optional[ThinkingAnalysis]:
        """Parse LLM response into ThinkingAnalysis."""
        try:
            # Extract JSON from response
            json_str = response
            if "```json" in response:
                json_str = response.split("```json")[1].split("```")[0]
            elif "```" in response:
                json_str = response.split("```")[1].split("```")[0]

            data = json.loads(json_str.strip())

            return ThinkingAnalysis(
                original_intent=data.get("original_intent", ""),
                actual_action=data.get("actual_action", ""),
                gap_description=data.get("gap_description", ""),
                cognitive_bias=data.get("cognitive_bias") or None,
            )
        except Exception as e:
            logger.warning("Failed to parse thinking analysis: %s", e)
            return None

    def _parse_semantic_context(self, response: str) -> SemanticContext:
        """Parse LLM response into SemanticContext."""
        try:
            json_str = response
            if "```json" in response:
                json_str = response.split("```json")[1].split("```")[0]
            elif "```" in response:
                json_str = response.split("```")[1].split("```")[0]

            data = json.loads(json_str.strip())

            return SemanticContext(
                user_intent=data.get("user_intent", ""),
                required_entities=data.get("required_entities", []),
                implied_workflow=data.get("implied_workflow", []),
                missing_knowledge=data.get("missing_knowledge", []),
            )
        except Exception as e:
            logger.warning("Failed to parse semantic context: %s", e)
            return SemanticContext("", [], [], [])

    def _generate_cognitive_suggestion(self, analysis: ThinkingAnalysis) -> str:
        """Generate suggestion based on cognitive analysis."""
        suggestions = {
            "premature_conclusion": "在 Skill 描述中添加强调：必须获取完整信息后再调用工具，不要急于下结论",
            "context_loss": "在 Memory 中添加工作流模板，提醒 Agent 在调用工具前检查所有必要参数是否已获取",
            "parameter_confusion": "在 Skill 描述中添加参数对照表，明确每个参数的来源和格式",
            "misunderstood_tool": "优化工具描述，添加使用场景示例和常见错误对比",
        }

        if analysis.cognitive_bias and analysis.cognitive_bias in suggestions:
            return suggestions[analysis.cognitive_bias]

        return "建议添加 Memory 记录，提醒 Agent 在思考和行动之间进行自我检查"
