"""Service API Protocol for bot lifecycle and queries.

Mirrors the public surface of
:class:`agentclaw.community.core.bot_management.services.bot_service.BotService`
that delivery adapters depend on. Method signatures use ``*args,
**kwargs`` because the concrete service has long, evolving call sites;
conformance is enforced structurally by
``tests/architecture/test_service_api_conformance.py`` so a missing
attribute fails CI rather than only at endpoint call time.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BotServiceProtocol(Protocol):
    """Service API for bot management — surface used by HTTP routers."""

    # ── Queries ────────────────────────────────────────────────────────
    def get_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    #: Resolves a bot by id **without deciding who may reach it** — the caller
    #: must adjudicate against the owner and primary key it returns, and must
    #: refuse with the same masked error an absent bot gives. Only for callers
    #: that may reach a bot they do not own, and so cannot use ``get_bot``.
    def get_bot_by_id(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_bot_by_ip_and_user(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_bots(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_bots_by_owner(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_bots_by_conditions(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_coding_bots_by_architect(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_domain_bots(self, *args: Any, **kwargs: Any) -> Any: ...

    def search_bots(self, *args: Any, **kwargs: Any) -> Any: ...

    def check_bot_name_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def check_create_bot_preflight(self, *args: Any, **kwargs: Any) -> Any: ...

    # Whether the owner has no Bots yet. ``create_flow`` keeps this separate
    # from Passport selection so the response can preserve its first-Bot field.
    def is_first_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    # Passport onboarding is based on the first live personal Bot, independently
    # from whether the owner already has service Bots.
    def is_first_personal_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    # The ceiling creation actually enforces (per-user policy, falling back to
    # the configured allocation limit). Exposed so a surface that *reports* the
    # quota resolves it the same way, instead of re-deriving the precedence and
    # drifting from what create rejects on.
    def get_bots_ceiling_for_owner(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_engine_paths(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_bot_work_path(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_bot_config_path(self, *args: Any, **kwargs: Any) -> Any: ...

    # ── Lifecycle / mutations ──────────────────────────────────────────
    def create_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_bot_ext(self, *args: Any, **kwargs: Any) -> Any: ...

    def ensure_hosted_workspace(self, *args: Any, **kwargs: Any) -> Any: ...

    def delete_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def restart_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def switch_engine(self, *args: Any, **kwargs: Any) -> Any: ...

    def release_bot_for_others(self, *args: Any, **kwargs: Any) -> Any: ...

    def hot_update_passport_token_to_device(self, *args: Any, **kwargs: Any) -> Any: ...

    # ── Bot lifecycle (called by other services / not the router) ──────
    # ``BotService`` exposes ``stop_bot`` / ``start_bot`` which are used by
    # ``OssToNasSwitchService``. They are not currently in any router but
    # are part of the cross-service surface; include them so the Protocol
    # is the single source of truth for what BotService offers consumers.
    def stop_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def start_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_status(self, *args: Any, **kwargs: Any) -> Any: ...
