"""Service API Protocol for bot collaborator management."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CollaboratorServiceProtocol(Protocol):
    """Service API for managing bot collaborators."""

    def add_collaborator(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_collaborators(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_collaborator(self, *args: Any, **kwargs: Any) -> Any: ...

    def remove_collaborator(self, *args: Any, **kwargs: Any) -> Any: ...

    def check_collaborator_permission(self, *args: Any, **kwargs: Any) -> Any: ...

    def check_permission(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_permission_level(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_user_collaborations(self, *args: Any, **kwargs: Any) -> Any: ...
