"""Service API Protocol for the end-to-end publish workflow."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PublishFlowServiceProtocol(Protocol):
    """Service API for orchestrating publish/restart flows + progress sync."""

    def process(self, *args: Any, **kwargs: Any) -> Any: ...

    def restart_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def scale_bot(self, *args: Any, **kwargs: Any) -> Any: ...

    def retry(self, *args: Any, **kwargs: Any) -> Any: ...

    def describe_publish(self, *args: Any, **kwargs: Any) -> Any: ...

    def sync_scale_progress(self, *args: Any, **kwargs: Any) -> Any: ...

    def sync_restart_progress(self, *args: Any, **kwargs: Any) -> Any: ...

    async def execute_rollback(self, *args: Any, **kwargs: Any) -> Any: ...
