from __future__ import annotations
from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class RepositoryCatalogServiceProtocol(Protocol):
    def list(self, *, path: str | None = None, orderby: str | None = None) -> list[dict[str, Any]]: ...
    def search(self, *, keyword: str, limit: int = 100) -> list[dict[str, Any]]: ...
    def tree(self) -> list[dict[str, Any]]: ...
    def detail(self, skill_id: str) -> dict[str, Any] | None: ...
    def sync(self) -> dict[str, Any]: ...
