SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'ac_skill_publication_attempt'
  AND COLUMN_NAME = 'materialization_retry_count'
  AND COLUMN_TYPE = 'int unsigned'
  AND IS_NULLABLE = 'NO'
  AND COLUMN_DEFAULT = '0';

SELECT CONSTRAINT_NAME, CHECK_CLAUSE
FROM information_schema.CHECK_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = DATABASE()
  AND CONSTRAINT_NAME = 'ck_skill_publication_attempt_status'
  AND CHECK_CLAUSE LIKE '%MATERIALIZATION_FAILED%';
