#!/usr/bin/env just --justfile

set dotenv-load := true
set positional-arguments := true

import 'justfiles/ctrl-baas.just'

import 'justfiles/lint.just'
import 'justfiles/test-common.just'
import 'justfiles/tests.just'

_default:
    @just --list --list-prefix '==> '

test-e2e-one test:
    source scripts/lib/test-stages.sh && run_one_e2e_test "{{test}}"

test-ci:
    ./scripts/ci_test.sh

test mode='bare' overlay='e2e-sqlite':
    source scripts/lib/pipeline.sh && run_ci_pipeline {{mode}} {{overlay}}

test-full:
    source scripts/lib/test-stages.sh && run_e2e_tests bare e2e-sqlite
    source scripts/lib/test-stages.sh && run_e2e_tests bare e2e-zdas

serve-docs port='8910':
    @./docs/openapi/serve-docs.sh {{port}}