from ._models import BotQpmConfigItem, BotQpmConfigListResult


class BotQpmManageService:
    """Bot QPM 配置管理 service 协议。"""

    def list_configs(self) -> BotQpmConfigListResult: ...
    def get_config(self, bot_id: str) -> BotQpmConfigItem | None: ...
    def upsert_config(self, *, bot_id: str, qpm: int) -> BotQpmConfigItem: ...
    def update_config(self, *, bot_id: str, qpm: int) -> BotQpmConfigItem | None: ...
    def delete_config(self, bot_id: str) -> bool: ...
