//! Onboard command execution.
use super::*;

pub(super) async fn execute_onboard(command: Commands, command_context: CommandContext) -> Result<()> {
    let Commands::Onboard {
            token,
            name,
            summary,
            skills,
            domains,
            scopes,
            binding_channels,
            web,
        } = command else { unreachable!("command dispatch mismatch") };
    let CommandContext { bcs_url, bcs_cookie, oauth_headers, debug, cli_json, .. } = command_context;

            if web {
                let token = get_token(token.as_deref())?;

                let skills_vec = skills
                    .as_deref()
                    .map(parse_skills_input)
                    .unwrap_or_default();

                let domains_vec = domains.as_deref().map(|d| {
                    d.split(',')
                        .map(|dom| dom.trim().to_string())
                        .collect::<Vec<_>>()
                });
                let scopes_vec = scopes.as_deref().map(|s| {
                    s.split(',')
                        .map(|sc| sc.trim().to_string())
                        .collect::<Vec<_>>()
                });

                // The onboard URL is generated by the BCS server.
                let client = create_client(
                    &bcs_url,
                    &token,
                    bcs_cookie.as_deref(),
                    oauth_headers.as_ref(),
                );

                let server_url = client
                    .get_onboard_url(
                        &token,
                        &name,
                        summary.as_deref(),
                        Some(&skills_vec),
                        domains_vec.as_deref(),
                        scopes_vec.as_deref(),
                        None,
                    )
                    .await;

                let url = match server_url {
                    Ok(Some(url)) => url,
                    Ok(None) => {
                        // Server does not support onboard URL generation (404) or is
                        // unreachable. The URL must come from the server — fail clearly.
                        return Err(anyhow!(
                            "BCS server does not support onboard URL generation. \
                             Please upgrade the BCS server to a version that provides the \
                             onboard URL endpoint."
                        ));
                    }
                    Err(err) => {
                        // Server returned 400 (config error) or other failure → surface the error
                        return Err(err);
                    }
                };

                if url.len() > 2000 {
                    eprintln!(
                        "Warning: Registration URL is very long ({} chars). Some browsers may truncate it.",
                        url.len()
                    );
                }

                if cli_json {
                    println!("{}", json!({"url": url}));
                } else {
                    println!("Registration URL:");
                    println!("{}", url);
                }
            } else {
                // Direct API mode
                let token = get_token(token.as_deref())?;
                let client = create_client(
                    &bcs_url,
                    &token,
                    bcs_cookie.as_deref(),
                    oauth_headers.as_ref(),
                );

                let skills_vec = skills
                    .as_deref()
                    .map(parse_skills_input)
                    .unwrap_or_default();
                let domains_vec = domains
                    .as_deref()
                    .map(|d| d.split(',').map(|dom| dom.trim().to_string()).collect())
                    .unwrap_or_default();
                let scopes_vec = scopes
                    .as_deref()
                    .map(|s| s.split(',').map(|sc| sc.trim().to_string()).collect())
                    .unwrap_or_default();

                // Parse binding_channels JSON
                let binding_channels_parsed: Option<bcs_protocol::BindingChannels> =
                    binding_channels
                        .as_deref()
                        .map(|s| serde_json::from_str(s))
                        .transpose()
                        .map_err(|e| anyhow!("Invalid binding_channels JSON: {}", e))?;

                debug_request!(
                    debug,
                    "POST",
                    "/bots/onboard",
                    json!({
                        "name": &name,
                        "summary": &summary,
                        "skills": &skills_vec,
                        "domains": &domains_vec,
                        "scopes": &scopes_vec,
                        "binding_channels": &binding_channels_parsed
                    })
                );

                let result = client
                    .onboard(
                        &name,
                        summary.as_deref(),
                        Some(skills_vec),
                        Some(domains_vec),
                        Some(scopes_vec),
                        binding_channels_parsed,
                    )
                    .await?;

                debug_response!(
                    debug,
                    "200",
                    json!({
                        "bot_id": &result.bot_uuid,
                        "onboarded": result.onboarded,
                        "name": &result.name,
                        "binding_results": &result.binding_results,
                        "unbound": &result.unbound
                    })
                );

                if cli_json {
                    println!("{}", serde_json::to_string(&result)?);
                } else {
                    println!("✓ Bot onboarded to BCS network:");
                    println!("  Bot ID: {}", result.bot_uuid);
                    println!("  Name: {}", result.name);

                    // Show binding results
                    if !result.binding_results.is_empty() {
                        println!("  Binding results:");
                        for (channel, res) in &result.binding_results {
                            let status = res
                                .get("status")
                                .and_then(|s| s.as_str())
                                .unwrap_or("unknown");
                            if status == "success" {
                                println!("    ✓ {}: {}", channel, status);
                            } else {
                                let msg = res.get("message").and_then(|m| m.as_str()).unwrap_or("");
                                println!("    ✗ {}: {} - {}", channel, status, msg);
                            }
                        }
                    }

                    // Show unbound channels
                    if !result.unbound.is_empty() {
                        println!("  Unbound channels:");
                        for ub in &result.unbound {
                            println!("    - {}", ub);
                        }
                    }
                }
            }

    Ok(())
}
