CREATE TABLE `ac_publish_operation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `publish_id` bigint(20) unsigned NOT NULL COMMENT 'agentclaw 发布单 id（eval_teardown 按 bot_uuid 时为 0）',
  `operation_kind` varchar(64) NOT NULL COMMENT 'PublishOperationKind',
  `stage` varchar(16) NOT NULL DEFAULT '' COMMENT 'verify/online/eval/空',
  `attempt` int(11) NOT NULL DEFAULT 1 COMMENT '重试代数；abandon 后 +1 开新行',
  `state` varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/id_recorded/completed/failed/abandoned',
  `request_id` varchar(128) NOT NULL COMMENT '确定性请求 id（关联/审计用，非幂等键）',
  `bot_uuid` varchar(128) NOT NULL DEFAULT '' COMMENT '目标 BaaS bot（创建类拿到前为空）',
  `baas_publish_id` bigint(20) unsigned DEFAULT NULL COMMENT 'BaaS 工作流 id，ID_RECORDED 时写入',
  `params` text DEFAULT NULL COMMENT '重发所需入参 JSON',
  `result` text DEFAULT NULL COMMENT '步骤结果 JSON（binding id / draft id / puid 等）',
  `last_error` text DEFAULT NULL COMMENT '最后一次步骤失败信息',
  `operator` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人',
  `env` varchar(32) NOT NULL COMMENT 'prod/pre/dev',
  `gmt_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY(`id`),
  UNIQUE KEY `uk_op`(`publish_id`, `operation_kind`, `stage`, `attempt`) GLOBAL,
  KEY `idx_pub_state`(`publish_id`, `state`) GLOBAL,
  KEY `idx_bot`(`bot_uuid`) GLOBAL
) DEFAULT CHARSET = utf8mb4 COMMENT = '发布操作幂等账本';
