/// SQLite DDL statements executed at local-mode startup.
/// All use IF NOT EXISTS for idempotency.
///
/// Excluded tables:
/// - `bcs_group_session` (singular, legacy, no store reference)
/// - database client test tables (non-business)
pub(super) const SQLITE_DDL_STATEMENTS: &[&str] = &[
    // ── schema_migrations ─────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_schema_migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        dialect TEXT NOT NULL,
        checksum TEXT NOT NULL,
        applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    // ── bots ──────────────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_bots (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        bot_uuid TEXT NOT NULL,
        name TEXT NOT NULL,
        bot_info TEXT DEFAULT NULL,
        session_token TEXT DEFAULT NULL,
        registered_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT DEFAULT NULL,
        visibility TEXT NOT NULL DEFAULT 'public',
        created_by TEXT DEFAULT NULL,
        actor_kind TEXT NOT NULL DEFAULT 'bot',
        status TEXT NOT NULL DEFAULT 'online',
        is_deleted INTEGER NOT NULL DEFAULT 0,
        agent_code TEXT DEFAULT NULL,
        task_claim_mode INTEGER NOT NULL DEFAULT 0,
        task_dream_mode INTEGER NOT NULL DEFAULT 0,
        user_visibility TEXT NOT NULL DEFAULT 'protected',
        friend_ext TEXT DEFAULT NULL,
        friend_check_in_strategy TEXT NOT NULL DEFAULT 'APPROVAL'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_bots_session_token ON bcs_bots(session_token)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_bots_bot_env ON bcs_bots(bot_uuid, env)",
    "CREATE INDEX IF NOT EXISTS idx_bots_actor_kind ON bcs_bots(actor_kind)",
    "CREATE INDEX IF NOT EXISTS idx_bots_agent_code ON bcs_bots(agent_code)",
    // ── friendships ───────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_friendships (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        left_bot TEXT NOT NULL,
        right_bot TEXT NOT NULL,
        env TEXT NOT NULL DEFAULT 'dev'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_friendships_pair ON bcs_friendships(left_bot, right_bot)",
    "CREATE INDEX IF NOT EXISTS idx_friendships_left ON bcs_friendships(left_bot)",
    "CREATE INDEX IF NOT EXISTS idx_friendships_right ON bcs_friendships(right_bot)",
    // ── friend_requests ───────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_friend_requests (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        request_id TEXT NOT NULL,
        from_bot TEXT NOT NULL,
        to_bot TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        env TEXT NOT NULL DEFAULT 'dev'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_friend_requests_req ON bcs_friend_requests(request_id)",
    "CREATE INDEX IF NOT EXISTS idx_friend_requests_from ON bcs_friend_requests(from_bot, status)",
    "CREATE INDEX IF NOT EXISTS idx_friend_requests_to ON bcs_friend_requests(to_bot, status)",
    // ── invite_codes ─────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_invite_codes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        code_hash TEXT NOT NULL UNIQUE,
        code_hint TEXT NOT NULL,
        status TEXT NOT NULL,
        bound_user_id TEXT NULL UNIQUE,
        bound_at INTEGER NULL,
        created_by TEXT NULL,
        env TEXT NOT NULL,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    "CREATE INDEX IF NOT EXISTS idx_invite_codes_env_status ON bcs_invite_codes(env, status)",
    // ── actor_relations ───────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_actor_relations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        from_id TEXT NOT NULL,
        to_id TEXT NOT NULL,
        env TEXT NOT NULL,
        kinds INTEGER NOT NULL DEFAULT 0,
        allow INTEGER NOT NULL DEFAULT 0,
        deny INTEGER NOT NULL DEFAULT 0,
        is_creator INTEGER NOT NULL DEFAULT 0
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_relations_from_to_env ON bcs_actor_relations(from_id, to_id, env)",
    "CREATE INDEX IF NOT EXISTS idx_relations_to_env ON bcs_actor_relations(to_id, env)",
    "CREATE INDEX IF NOT EXISTS idx_relations_from_env_creator ON bcs_actor_relations(from_id, env, is_creator)",
    // ── providers ─────────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_providers (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        provider_id TEXT NOT NULL,
        env TEXT NOT NULL,
        name TEXT NOT NULL,
        config TEXT NOT NULL,
        disabled INTEGER NOT NULL DEFAULT 0,
        created_by TEXT NOT NULL,
        owners TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_providers_env ON bcs_providers(env, provider_id)",

    // ── organizations ─────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_organizations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT DEFAULT NULL,
        managing_provider_id TEXT NOT NULL,
        disabled INTEGER NOT NULL DEFAULT 0
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_org_env_code ON bcs_organizations(env, code)",
    "CREATE INDEX IF NOT EXISTS idx_org_env_disabled ON bcs_organizations(env, disabled)",
    "CREATE INDEX IF NOT EXISTS idx_org_env_provider ON bcs_organizations(env, managing_provider_id)",

    // ── organization_members ──────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_organization_members (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        organization_code TEXT NOT NULL,
        bot_uuid TEXT NOT NULL,
        role TEXT DEFAULT NULL,
        disabled INTEGER NOT NULL DEFAULT 0
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_org_member ON bcs_organization_members(env, organization_code, bot_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_member_bot ON bcs_organization_members(env, bot_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_member_org_disabled_role ON bcs_organization_members(env, organization_code, disabled, role)",

    // ── provider_bot_bindings ─────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_provider_bot_bindings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        bot_uuid TEXT NOT NULL,
        provider_id TEXT NOT NULL,
        provider_bot_ref TEXT NOT NULL,
        env TEXT NOT NULL,
        disabled INTEGER NOT NULL DEFAULT 0
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_provider_ref_env ON bcs_provider_bot_bindings(env, provider_id, provider_bot_ref)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_bot_uuid_env ON bcs_provider_bot_bindings(env, bot_uuid)",
    // ── channel bindings ─────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_channel_bindings (
        id TEXT PRIMARY KEY,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        channel_type TEXT NOT NULL,
        account_ref TEXT NOT NULL,
        target_json TEXT NOT NULL,
        group_chat_scope TEXT DEFAULT NULL,
        visibility TEXT NOT NULL,
        env TEXT NOT NULL,
        status TEXT NOT NULL,
        created_by TEXT DEFAULT NULL,
        config_json TEXT NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_channel_bindings_account ON bcs_channel_bindings(channel_type, account_ref, status)",
    // ── channel conversations ─────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_channel_conversations (
        binding_id TEXT NOT NULL,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        im_conversation_id TEXT NOT NULL,
        im_conversation_type TEXT NOT NULL,
        session_scope TEXT NOT NULL,
        im_user_id TEXT NOT NULL DEFAULT '',
        bcs_session_id TEXT NOT NULL,
        last_active_at INTEGER NOT NULL,
        PRIMARY KEY (binding_id, im_conversation_id, session_scope, im_user_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_channel_conversations_session ON bcs_channel_conversations(binding_id, bcs_session_id)",
    "CREATE INDEX IF NOT EXISTS idx_channel_conversations_bcs_session ON bcs_channel_conversations(bcs_session_id, binding_id)",
    // ── channel IM participants ───────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_channel_im_participants (
        channel_type TEXT NOT NULL,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        account_ref TEXT NOT NULL,
        im_user_id TEXT NOT NULL,
        actor_id TEXT NOT NULL,
        display_name TEXT DEFAULT NULL,
        PRIMARY KEY (channel_type, account_ref, im_user_id)
    )",
    // ── HumanInput IM requests ────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_human_input_requests (
        request_id TEXT PRIMARY KEY,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        session_id TEXT NOT NULL,
        run_id TEXT NOT NULL,
        node_id TEXT NOT NULL,
        binding_id TEXT NOT NULL,
        channel_type TEXT NOT NULL,
        account_ref TEXT NOT NULL,
        notification_mode TEXT NOT NULL,
        reply_scope_key TEXT NOT NULL,
        active_slot_key TEXT DEFAULT NULL,
        assignee_actor_id TEXT NOT NULL,
        im_conversation_id TEXT NOT NULL,
        im_conversation_type TEXT NOT NULL,
        im_user_id TEXT DEFAULT NULL,
        node_display_name TEXT NOT NULL,
        notification_text TEXT NOT NULL,
        deadline_ms INTEGER NOT NULL,
        status TEXT NOT NULL,
        provider_message_ref TEXT DEFAULT NULL,
        delivery_attempts INTEGER NOT NULL DEFAULT 0,
        last_delivery_error TEXT DEFAULT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        activated_at INTEGER DEFAULT NULL,
        responded_at INTEGER DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_human_input_active_slot ON bcs_human_input_requests(active_slot_key)",
    "CREATE INDEX IF NOT EXISTS idx_human_input_scope_status ON bcs_human_input_requests(reply_scope_key, status, deadline_ms, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_human_input_run_node ON bcs_human_input_requests(run_id, node_id)",
    // ── provider_credentials ──────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_provider_credentials (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        provider_id TEXT NOT NULL,
        env TEXT NOT NULL,
        credential_kind TEXT NOT NULL,
        secret_value TEXT NOT NULL,
        disabled INTEGER NOT NULL DEFAULT 0
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_provider_cred_kind ON bcs_provider_credentials(env, provider_id, credential_kind)",
    "CREATE INDEX IF NOT EXISTS idx_credential_lookup ON bcs_provider_credentials(env, credential_kind, secret_value)",
    // ── user_identities ───────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_user_identities (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id TEXT NOT NULL,
        auth_source TEXT NOT NULL,
        external_user_id TEXT NOT NULL,
        user_name TEXT DEFAULT NULL,
        external_user_name TEXT DEFAULT NULL,
        avatar TEXT DEFAULT NULL,
        token TEXT DEFAULT NULL,
        token_expire_at TEXT DEFAULT NULL,
        env TEXT NOT NULL,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_user_id ON bcs_user_identities(user_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_external ON bcs_user_identities(auth_source, external_user_id, env)",
    "CREATE INDEX IF NOT EXISTS idx_external ON bcs_user_identities(external_user_id, env)",
    // ── groups ────────────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_groups (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        group_id TEXT NOT NULL,
        label TEXT DEFAULT NULL,
        status TEXT NOT NULL,
        driver_bot TEXT NOT NULL,
        originator TEXT DEFAULT NULL,
        env TEXT NOT NULL,
        routing_policy_json TEXT DEFAULT NULL,
        context TEXT DEFAULT NULL,
        opening_message_json TEXT DEFAULT NULL,
        group_kind TEXT NOT NULL DEFAULT 'normal',
        dm_pair_key TEXT DEFAULT NULL,
        service_group_uuid TEXT DEFAULT NULL,
        service_mode TEXT DEFAULT NULL,
        version INTEGER NOT NULL DEFAULT 1,
        record_status TEXT NOT NULL DEFAULT 'active',
        lifecycle_status TEXT NOT NULL DEFAULT 'active',
        group_strategy TEXT NOT NULL DEFAULT 'chat',
        participants TEXT DEFAULT NULL,
        service_spec TEXT DEFAULT NULL,
        created_by TEXT DEFAULT NULL,
        visibility TEXT NOT NULL DEFAULT 'private'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_groups_group_env ON bcs_groups(group_id, env)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_groups_dm_pair ON bcs_groups(env, dm_pair_key)",
    "CREATE INDEX IF NOT EXISTS idx_groups_driver ON bcs_groups(driver_bot)",
    "CREATE INDEX IF NOT EXISTS idx_groups_service_uuid ON bcs_groups(service_group_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_groups_label ON bcs_groups(label)",
    "CREATE INDEX IF NOT EXISTS idx_groups_visibility ON bcs_groups(visibility)",
    // ── chat_runs (Direct Chat async governance, #1546) ─────
    "CREATE TABLE IF NOT EXISTS bcs_chat_runs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        run_id TEXT NOT NULL,
        bot_uuid TEXT NOT NULL,
        from_bot_id TEXT NOT NULL,
        session_key TEXT NOT NULL,
        state TEXT NOT NULL,
        accumulated_content TEXT,
        error_message TEXT,
        original_request TEXT,
        completed_at_ms INTEGER,
        expires_at_ms INTEGER NOT NULL,
        version INTEGER NOT NULL,
        content_truncated INTEGER NOT NULL DEFAULT 0,
        client TEXT,
        response_mode TEXT NOT NULL,
        completion_policy TEXT NOT NULL,
        delivery_ack_at_ms INTEGER,
        CONSTRAINT uk_env_run_id UNIQUE (env, run_id)
    )",
    "CREATE INDEX IF NOT EXISTS idx_env_expires ON bcs_chat_runs(env, state, expires_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_env_completed ON bcs_chat_runs(env, state, completed_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_env_from_bot ON bcs_chat_runs(env, from_bot_id)",
    "CREATE INDEX IF NOT EXISTS idx_env_bot ON bcs_chat_runs(env, bot_uuid)",
    // ── group_participants ────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_group_participants (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        group_id TEXT NOT NULL,
        bot_uuid TEXT NOT NULL,
        role TEXT NOT NULL,
        env TEXT NOT NULL,
        actor_kind TEXT NOT NULL DEFAULT 'bot',
        mode TEXT NOT NULL DEFAULT 'auto',
        tags_json TEXT DEFAULT NULL,
        message_view_scope TEXT NOT NULL DEFAULT 'full'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_participants_env_group_bot ON bcs_group_participants(env, group_id, bot_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_participants_bot ON bcs_group_participants(bot_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_participants_group ON bcs_group_participants(group_id)",
    // ── group_sessions ────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_group_sessions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        session_id TEXT NOT NULL,
        group_id TEXT NOT NULL,
        env TEXT NOT NULL DEFAULT 'prod',
        status TEXT NOT NULL DEFAULT 'running',
        session_kind TEXT NOT NULL DEFAULT 'chat',
        message_visibility_version INTEGER NOT NULL DEFAULT 0,
        session_title TEXT DEFAULT NULL,
        group_version INTEGER DEFAULT NULL,
        caller_id TEXT DEFAULT NULL,
        input TEXT DEFAULT NULL,
        output TEXT DEFAULT NULL,
        error_message TEXT DEFAULT NULL,
        callback_status TEXT DEFAULT NULL,
        callback_lease_owner TEXT DEFAULT NULL,
        callback_lease_token INTEGER DEFAULT NULL,
        callback_lease_until_ms INTEGER DEFAULT NULL,
        activation_count INTEGER NOT NULL DEFAULT 1,
        caller_principal TEXT DEFAULT NULL,
        created_by TEXT DEFAULT NULL,
        participants TEXT NOT NULL,
        completed_at INTEGER DEFAULT NULL,
        meta TEXT DEFAULT NULL,
        current_msg_seq INTEGER NOT NULL DEFAULT 0,
        participant_join_seq TEXT DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sessions_id ON bcs_group_sessions(env, session_id)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_group_status ON bcs_group_sessions(env, group_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_group_kind_status ON bcs_group_sessions(env, group_id, session_kind, status)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_caller_principal ON bcs_group_sessions(env, caller_principal)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_callback_status ON bcs_group_sessions(env, callback_status)",
    "CREATE INDEX IF NOT EXISTS idx_session_callback_recovery ON bcs_group_sessions(env, session_kind, status, callback_status, callback_lease_token, callback_lease_until_ms, session_id)",
    // ── session_participants ──────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_session_participants (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        session_id TEXT NOT NULL,
        group_id TEXT NOT NULL,
        bot_uuid TEXT NOT NULL,
        role TEXT NOT NULL,
        env TEXT NOT NULL DEFAULT 'prod',
        collected INTEGER NOT NULL DEFAULT 0,
        collected_at TEXT
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_session_participants_env_session_bot ON bcs_session_participants(env, session_id, bot_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_session_participants_bot ON bcs_session_participants(env, bot_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_session_participants_session ON bcs_session_participants(env, session_id)",
    // ── messages ──────────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_messages (
        message_id TEXT NOT NULL PRIMARY KEY,
        group_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        session_seq INTEGER NOT NULL,
        env TEXT NOT NULL,
        sender_id TEXT NOT NULL,
        sender_type TEXT NOT NULL,
        message_type TEXT NOT NULL,
        content TEXT NOT NULL,
        client_msg_id TEXT DEFAULT NULL,
        owner_bot_id TEXT DEFAULT NULL,
        visibility_domain TEXT DEFAULT NULL,
        audience_kind TEXT DEFAULT NULL,
        audience_actor_ids_json TEXT DEFAULT NULL,
        status TEXT DEFAULT 'normal',
        created_at INTEGER NOT NULL,
        ttl_until INTEGER DEFAULT NULL,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        run_id TEXT NOT NULL DEFAULT ''
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_messages_session_seq ON bcs_messages(session_id, session_seq)",
    "CREATE INDEX IF NOT EXISTS idx_messages_group_created ON bcs_messages(group_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_messages_group_session ON bcs_messages(group_id, session_id)",
    "CREATE INDEX IF NOT EXISTS idx_messages_session_created ON bcs_messages(session_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_messages_session_sender_created ON bcs_messages(session_id, sender_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_messages_session_type_created ON bcs_messages(session_id, message_type, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_messages_session_audience_created ON bcs_messages(session_id, visibility_domain, audience_kind, created_at, session_seq)",
    // ── collaboration_definitions ─────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_collaboration_definitions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        definition_id TEXT NOT NULL,
        version INTEGER NOT NULL,
        name TEXT NOT NULL,
        description TEXT DEFAULT NULL,
        source_format TEXT NOT NULL DEFAULT 'yaml',
        content_hash TEXT NOT NULL,
        blob_id TEXT DEFAULT NULL,
        yaml_text TEXT DEFAULT NULL,
        normalized_json TEXT DEFAULT NULL,
        metadata_json TEXT DEFAULT NULL,
        record_status TEXT NOT NULL DEFAULT 'active',
        created_by TEXT DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_collab_def_version ON bcs_collaboration_definitions(env, definition_id, version)",
    "CREATE INDEX IF NOT EXISTS idx_collab_def_hash ON bcs_collaboration_definitions(env, content_hash)",
    "CREATE INDEX IF NOT EXISTS idx_collab_def_blob ON bcs_collaboration_definitions(env, blob_id)",
    "CREATE INDEX IF NOT EXISTS idx_collab_def_status ON bcs_collaboration_definitions(env, record_status)",
    // ── collaboration_definition_blobs ────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_collaboration_definition_blobs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        blob_id TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        content_encoding TEXT NOT NULL DEFAULT 'identity',
        content_size INTEGER NOT NULL,
        content BLOB DEFAULT NULL,
        external_uri TEXT DEFAULT NULL,
        created_by TEXT DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_collab_blob_id ON bcs_collaboration_definition_blobs(env, blob_id)",
    "CREATE INDEX IF NOT EXISTS idx_collab_blob_hash ON bcs_collaboration_definition_blobs(env, content_hash)",
    // ── collaboration_events ──────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_collaboration_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        state_machine_run_id TEXT NOT NULL,
        node_id TEXT DEFAULT NULL,
        attempt INTEGER DEFAULT NULL,
        event_type TEXT NOT NULL,
        payload_json TEXT DEFAULT NULL,
        created_at_ms INTEGER NOT NULL,
        record_status TEXT NOT NULL DEFAULT 'active'
    )",
    "CREATE INDEX IF NOT EXISTS idx_collab_events_run ON bcs_collaboration_events(env, state_machine_run_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_collab_events_run_node ON bcs_collaboration_events(env, state_machine_run_id, node_id, attempt, id)",
    "CREATE INDEX IF NOT EXISTS idx_collab_events_type_time ON bcs_collaboration_events(env, event_type, created_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_collab_events_record_status ON bcs_collaboration_events(env, record_status)",
    // ── collaboration_templates ───────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_collaboration_templates (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        template_id TEXT NOT NULL,
        source_type TEXT NOT NULL DEFAULT 'system',
        visibility TEXT NOT NULL DEFAULT 'public',
        owner_user_id TEXT DEFAULT NULL,
        priority INTEGER NOT NULL DEFAULT 4294967295,
        record_status TEXT NOT NULL DEFAULT 'active',
        created_by TEXT DEFAULT NULL,
        updated_by TEXT DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_bct_template ON bcs_collaboration_templates(env, template_id)",
    "CREATE INDEX IF NOT EXISTS idx_bct_env_status_priority ON bcs_collaboration_templates(env, record_status, priority, template_id)",
    "CREATE INDEX IF NOT EXISTS idx_bct_env_visibility_priority ON bcs_collaboration_templates(env, visibility, record_status, priority, template_id)",
    "CREATE INDEX IF NOT EXISTS idx_bct_env_owner_status ON bcs_collaboration_templates(env, owner_user_id, record_status, priority, template_id)",
    // ── collaboration_template_contents ───────────────────
    "CREATE TABLE IF NOT EXISTS bcs_collaboration_template_contents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        template_id TEXT NOT NULL,
        lang TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT DEFAULT NULL,
        participant_summary_json TEXT NOT NULL,
        definition_json TEXT NOT NULL,
        yaml_text TEXT NOT NULL,
        yaml_sha256 TEXT NOT NULL,
        version INTEGER NOT NULL DEFAULT 1,
        record_status TEXT NOT NULL DEFAULT 'active'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_bctc_template_lang ON bcs_collaboration_template_contents(env, template_id, lang)",
    "CREATE INDEX IF NOT EXISTS idx_bctc_env_lang_status ON bcs_collaboration_template_contents(env, lang, record_status, template_id)",
    "CREATE INDEX IF NOT EXISTS idx_bctc_env_hash ON bcs_collaboration_template_contents(env, yaml_sha256)",
    // ── collaboration_template_tags ───────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_collaboration_template_tags (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        template_id TEXT NOT NULL,
        tag TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_bctt_template_tag ON bcs_collaboration_template_tags(env, template_id, tag)",
    "CREATE INDEX IF NOT EXISTS idx_bctt_env_tag ON bcs_collaboration_template_tags(env, tag, template_id)",
    // ── state_machine_runs ────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_state_machine_runs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        run_id TEXT NOT NULL,
        root_run_id TEXT DEFAULT NULL,
        rerun_of TEXT DEFAULT NULL,
        definition_id TEXT NOT NULL,
        definition_version INTEGER NOT NULL,
        group_id TEXT NOT NULL,
        group_version INTEGER NOT NULL,
        session_id TEXT NOT NULL,
        session_activation_count INTEGER DEFAULT NULL,
        created_by TEXT DEFAULT NULL,
        status TEXT NOT NULL,
        input_json TEXT DEFAULT NULL,
        opening_message_override_json TEXT DEFAULT NULL,
        output_text TEXT DEFAULT NULL,
        error_message TEXT DEFAULT NULL,
        created_at_ms INTEGER NOT NULL,
        updated_at_ms INTEGER NOT NULL,
        completed_at_ms INTEGER DEFAULT NULL,
        record_status TEXT NOT NULL DEFAULT 'active'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sm_run_id ON bcs_state_machine_runs(env, run_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sm_run_rerun_of ON bcs_state_machine_runs(env, rerun_of)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_root ON bcs_state_machine_runs(env, root_run_id, created_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_session ON bcs_state_machine_runs(env, session_id)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_created_by ON bcs_state_machine_runs(env, created_by, created_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_group_status ON bcs_state_machine_runs(env, group_id, status, created_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_status_updated ON bcs_state_machine_runs(env, status, updated_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_definition ON bcs_state_machine_runs(env, definition_id, definition_version)",
    "CREATE INDEX IF NOT EXISTS idx_sm_runs_record_status ON bcs_state_machine_runs(env, record_status)",
    // ── state_machine_node_runs ───────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_state_machine_node_runs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        run_id TEXT NOT NULL,
        node_id TEXT NOT NULL,
        status TEXT NOT NULL,
        attempt INTEGER NOT NULL DEFAULT 0,
        node_timeout_ms INTEGER DEFAULT NULL,
        timeout_deadline_ms INTEGER DEFAULT NULL,
        max_attempts INTEGER NOT NULL DEFAULT 1,
        assignee_bot_id TEXT NOT NULL,
        outcome TEXT DEFAULT NULL,
        responded_by TEXT DEFAULT NULL,
        delivery_request_id TEXT DEFAULT NULL,
        bot_delivery_run_id TEXT DEFAULT NULL,
        artifact_text TEXT DEFAULT NULL,
        error_message TEXT DEFAULT NULL,
        started_at_ms INTEGER DEFAULT NULL,
        completed_at_ms INTEGER DEFAULT NULL,
        record_status TEXT NOT NULL DEFAULT 'active'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sm_node_run ON bcs_state_machine_node_runs(env, run_id, node_id)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_run_status ON bcs_state_machine_node_runs(env, run_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_status_started ON bcs_state_machine_node_runs(env, status, started_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_timeout_deadline ON bcs_state_machine_node_runs(env, status, timeout_deadline_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_assignee_status ON bcs_state_machine_node_runs(env, assignee_bot_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_delivery_request ON bcs_state_machine_node_runs(env, delivery_request_id)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_bot_delivery_run ON bcs_state_machine_node_runs(env, bot_delivery_run_id)",
    "CREATE INDEX IF NOT EXISTS idx_sm_nodes_record_status ON bcs_state_machine_node_runs(env, record_status)",
    // ── state_machine_delivery_correlations ───────────────
    "CREATE TABLE IF NOT EXISTS bcs_state_machine_delivery_correlations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        state_machine_run_id TEXT NOT NULL,
        node_id TEXT NOT NULL,
        attempt INTEGER NOT NULL,
        assignee_bot_id TEXT NOT NULL,
        delivery_request_id TEXT NOT NULL,
        bot_delivery_run_id TEXT DEFAULT NULL,
        created_at_ms INTEGER NOT NULL,
        updated_at_ms INTEGER NOT NULL,
        record_status TEXT NOT NULL DEFAULT 'active'
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sm_corr_delivery_request ON bcs_state_machine_delivery_correlations(env, delivery_request_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sm_corr_bot_delivery_run ON bcs_state_machine_delivery_correlations(env, bot_delivery_run_id)",
    "CREATE INDEX IF NOT EXISTS idx_sm_corr_run_node_attempt ON bcs_state_machine_delivery_correlations(env, state_machine_run_id, node_id, attempt)",
    "CREATE INDEX IF NOT EXISTS idx_sm_corr_assignee ON bcs_state_machine_delivery_correlations(env, assignee_bot_id, created_at_ms)",
    "CREATE INDEX IF NOT EXISTS idx_sm_corr_record_status ON bcs_state_machine_delivery_correlations(env, record_status)",
    // ── state_machine_definition_snapshots ────────────────
    "CREATE TABLE IF NOT EXISTS bcs_state_machine_definition_snapshots (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        run_id TEXT NOT NULL,
        group_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        group_version INTEGER NOT NULL,
        definition_id TEXT NOT NULL,
        definition_version INTEGER NOT NULL,
        definition_content_hash TEXT NOT NULL,
        snapshot_blob_id TEXT DEFAULT NULL,
        snapshot_json TEXT DEFAULT NULL,
        source_format TEXT NOT NULL DEFAULT 'yaml',
        resolved_participant_bindings_json TEXT DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_def_snapshot_run ON bcs_state_machine_definition_snapshots(env, run_id)",
    "CREATE INDEX IF NOT EXISTS idx_def_snapshot_group_version ON bcs_state_machine_definition_snapshots(env, group_id, group_version)",
    "CREATE INDEX IF NOT EXISTS idx_def_snapshot_definition ON bcs_state_machine_definition_snapshots(env, definition_id, definition_version)",
    // ── group_runtime_bindings ────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_group_runtime_bindings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        group_id TEXT NOT NULL,
        group_version INTEGER NOT NULL,
        next_group_version INTEGER NOT NULL DEFAULT 2147483647,
        default_definition_id TEXT DEFAULT NULL,
        default_definition_version INTEGER DEFAULT NULL,
        definition_content_hash TEXT DEFAULT NULL,
        definition_blob_id TEXT DEFAULT NULL,
        auto_start_on_service_invocation INTEGER NOT NULL DEFAULT 0,
        record_status TEXT NOT NULL DEFAULT 'active',
        updated_by TEXT DEFAULT NULL,
        participant_bindings_json TEXT DEFAULT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_group_binding_version ON bcs_group_runtime_bindings(env, group_id, group_version)",
    "CREATE INDEX IF NOT EXISTS idx_group_binding_current ON bcs_group_runtime_bindings(env, group_id, record_status, next_group_version)",
    "CREATE INDEX IF NOT EXISTS idx_group_binding_effective ON bcs_group_runtime_bindings(env, group_id, record_status, group_version, next_group_version)",
    "CREATE INDEX IF NOT EXISTS idx_group_binding_definition ON bcs_group_runtime_bindings(env, default_definition_id, default_definition_version)",
    // ── identity_links ────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_identity_links (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        internal_id TEXT NOT NULL,
        auth_source TEXT NOT NULL,
        external_id TEXT NOT NULL,
        external_owner_id TEXT DEFAULT NULL,
        provider_id TEXT DEFAULT NULL,
        actor_kind TEXT NOT NULL,
        env TEXT NOT NULL,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_identity ON bcs_identity_links(auth_source, external_id, external_owner_id, provider_id, env)",
    "CREATE INDEX IF NOT EXISTS idx_identity_internal ON bcs_identity_links(internal_id, env)",
    "CREATE INDEX IF NOT EXISTS idx_identity_external ON bcs_identity_links(external_id, env)",
    "CREATE INDEX IF NOT EXISTS idx_identity_provider ON bcs_identity_links(provider_id, external_id, env)",
    // ── service_group_templates ───────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_service_group_templates (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        uuid TEXT NOT NULL,
        version INTEGER NOT NULL DEFAULT 1,
        publish_status TEXT NOT NULL DEFAULT 'draft',
        name TEXT NOT NULL,
        description TEXT DEFAULT NULL,
        participants TEXT NOT NULL,
        service_mode TEXT NOT NULL,
        mode_config TEXT DEFAULT NULL,
        callback_config TEXT DEFAULT NULL,
        max_concurrency INTEGER NOT NULL DEFAULT -1,
        created_by TEXT NOT NULL,
        modified_by TEXT NOT NULL,
        env TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_sgt_uuid_version ON bcs_service_group_templates(uuid, version)",
    "CREATE INDEX IF NOT EXISTS idx_sgt_uuid ON bcs_service_group_templates(uuid)",
    "CREATE INDEX IF NOT EXISTS idx_sgt_created_by ON bcs_service_group_templates(created_by)",
    // ── service_group_instances ───────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_service_group_instances (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        group_id TEXT NOT NULL,
        service_group_uuid TEXT NOT NULL,
        service_group_version INTEGER NOT NULL,
        instance_meta TEXT DEFAULT NULL,
        callback_status TEXT DEFAULT NULL,
        reactivation_log TEXT DEFAULT NULL,
        instance_result TEXT DEFAULT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_sgi_group_id ON bcs_service_group_instances(group_id)",
    "CREATE INDEX IF NOT EXISTS idx_sgi_service_group_uuid ON bcs_service_group_instances(service_group_uuid)",
    "CREATE INDEX IF NOT EXISTS idx_sgi_callback_status ON bcs_service_group_instances(callback_status)",

    // ── session_files ─────────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_session_files (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        gmt_create TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL,
        file_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        owner_actor_kind TEXT NOT NULL,
        owner_actor_id TEXT NOT NULL,
        file_name TEXT NOT NULL,
        mime_type TEXT NOT NULL,
        size INTEGER NOT NULL,
        sha256 TEXT,
        storage_backend TEXT NOT NULL,
        object_handle TEXT NOT NULL,
        status TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_session_file ON bcs_session_files (env, session_id, file_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_env_file_id ON bcs_session_files (env, file_id)",
    "CREATE INDEX IF NOT EXISTS idx_session_files_session ON bcs_session_files (env, session_id, gmt_create)",
    // ── public Eventing ──────────────────────────────────
    "CREATE TABLE IF NOT EXISTS bcs_event_subscriptions (
        subscription_id TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL,
        scope_type TEXT NOT NULL,
        scope_id TEXT NOT NULL,
        status TEXT NOT NULL,
        current_revision INTEGER NOT NULL,
        created_by_type TEXT NOT NULL,
        created_by_id TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        deleted_at TEXT DEFAULT NULL,
        env TEXT NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_event_subscription_scope
        ON bcs_event_subscriptions(env, scope_type, scope_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_event_subscription_status
        ON bcs_event_subscriptions(env, status, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_event_subscription_creator
        ON bcs_event_subscriptions(env, created_by_type, created_by_id)",
    "CREATE TABLE IF NOT EXISTS bcs_event_subscription_revisions (
        subscription_id TEXT NOT NULL,
        revision INTEGER NOT NULL,
        event_filters_json TEXT NOT NULL,
        payload_mode TEXT NOT NULL,
        endpoint_url TEXT NOT NULL,
        request_timeout_ms INTEGER NOT NULL,
        activated_at TEXT NOT NULL,
        retired_at TEXT DEFAULT NULL,
        env TEXT NOT NULL,
        PRIMARY KEY(subscription_id, revision)
    )",
    "CREATE INDEX IF NOT EXISTS idx_event_revision_active
        ON bcs_event_subscription_revisions(env, subscription_id, retired_at)",
    "CREATE TABLE IF NOT EXISTS bcs_event_scope_epochs (
        env TEXT NOT NULL,
        scope_type TEXT NOT NULL,
        scope_id TEXT NOT NULL,
        epoch INTEGER NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(env, scope_type, scope_id)
    )",
    "CREATE TABLE IF NOT EXISTS bcs_event_streams (
        env TEXT NOT NULL,
        stream_key TEXT NOT NULL,
        last_sequence INTEGER NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(env, stream_key)
    )",
    "CREATE TABLE IF NOT EXISTS bcs_events (
        event_id TEXT NOT NULL PRIMARY KEY,
        event_type TEXT NOT NULL,
        schema_version TEXT NOT NULL,
        producer TEXT NOT NULL,
        producer_key TEXT NOT NULL,
        subject_type TEXT NOT NULL,
        subject_id TEXT NOT NULL,
        group_id TEXT DEFAULT NULL,
        session_id TEXT DEFAULT NULL,
        task_id TEXT DEFAULT NULL,
        run_id TEXT DEFAULT NULL,
        stream_key TEXT NOT NULL,
        sequence INTEGER NOT NULL,
        actor_json TEXT DEFAULT NULL,
        correlation_id TEXT DEFAULT NULL,
        causation_event_id TEXT DEFAULT NULL,
        trace_id TEXT DEFAULT NULL,
        data_json TEXT NOT NULL,
        occurred_at TEXT NOT NULL,
        recorded_at TEXT NOT NULL,
        fanout_status TEXT NOT NULL,
        retention_until TEXT NOT NULL,
        env TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_event_producer
        ON bcs_events(env, producer, producer_key, event_type)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_event_stream_sequence
        ON bcs_events(env, stream_key, sequence)",
    "CREATE INDEX IF NOT EXISTS idx_event_fanout_status
        ON bcs_events(env, fanout_status, recorded_at)",
    "CREATE INDEX IF NOT EXISTS idx_event_scope_type
        ON bcs_events(env, group_id, session_id, event_type, recorded_at)",
    "CREATE INDEX IF NOT EXISTS idx_event_causation
        ON bcs_events(env, causation_event_id)",
    "CREATE INDEX IF NOT EXISTS idx_event_retention
        ON bcs_events(env, retention_until, fanout_status)",
    "CREATE TABLE IF NOT EXISTS bcs_event_fanout_targets (
        target_id TEXT NOT NULL PRIMARY KEY,
        event_id TEXT NOT NULL,
        subscription_id TEXT NOT NULL,
        subscription_revision INTEGER NOT NULL,
        purpose TEXT NOT NULL,
        replay_request_id TEXT NOT NULL DEFAULT '',
        replay_of_delivery_id TEXT DEFAULT NULL,
        depends_on_target_id TEXT DEFAULT NULL,
        status TEXT NOT NULL,
        lease_owner TEXT DEFAULT NULL,
        lease_until TEXT DEFAULT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        materialized_at TEXT DEFAULT NULL,
        cancelled_at TEXT DEFAULT NULL,
        env TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_event_target_idempotency
        ON bcs_event_fanout_targets(env, subscription_id, subscription_revision, event_id, purpose, replay_request_id)",
    "CREATE INDEX IF NOT EXISTS idx_event_target_pending
        ON bcs_event_fanout_targets(env, status, lease_until, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_event_target_dependency
        ON bcs_event_fanout_targets(env, depends_on_target_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_event_target_subscription
        ON bcs_event_fanout_targets(env, subscription_id, subscription_revision, status)",
    "CREATE TABLE IF NOT EXISTS bcs_event_deliveries (
        delivery_id TEXT NOT NULL PRIMARY KEY,
        fanout_target_id TEXT NOT NULL,
        event_id TEXT NOT NULL,
        subscription_id TEXT NOT NULL,
        subscription_revision INTEGER NOT NULL,
        stream_key TEXT NOT NULL,
        sequence INTEGER NOT NULL,
        payload_bytes BLOB NOT NULL,
        payload_sha256 TEXT NOT NULL,
        status TEXT NOT NULL,
        attempt_count INTEGER NOT NULL DEFAULT 0,
        first_attempt_at TEXT DEFAULT NULL,
        last_attempt_at TEXT DEFAULT NULL,
        next_attempt_at TEXT DEFAULT NULL,
        lease_owner TEXT DEFAULT NULL,
        lease_until TEXT DEFAULT NULL,
        last_http_status INTEGER DEFAULT NULL,
        last_error_category TEXT DEFAULT NULL,
        last_error_summary TEXT DEFAULT NULL,
        dead_lettered_at TEXT DEFAULT NULL,
        cancelled_at TEXT DEFAULT NULL,
        skipped_at TEXT DEFAULT NULL,
        skip_actor TEXT DEFAULT NULL,
        skip_reason TEXT DEFAULT NULL,
        replay_of_delivery_id TEXT DEFAULT NULL,
        resolved_by_delivery_id TEXT DEFAULT NULL,
        resolved_at TEXT DEFAULT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        succeeded_at TEXT DEFAULT NULL,
        env TEXT NOT NULL
    )",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_event_delivery_target
        ON bcs_event_deliveries(env, fanout_target_id)",
    "CREATE INDEX IF NOT EXISTS idx_event_claim_due
        ON bcs_event_deliveries(env, status, next_attempt_at, lease_until)",
    "CREATE INDEX IF NOT EXISTS idx_event_strict_lane
        ON bcs_event_deliveries(env, subscription_id, stream_key, status, sequence)",
    "CREATE INDEX IF NOT EXISTS idx_event_delivery_subscription
        ON bcs_event_deliveries(env, subscription_id, status, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_event_delivery_replay
        ON bcs_event_deliveries(env, replay_of_delivery_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_event_delivery_retention
        ON bcs_event_deliveries(env, status, succeeded_at, dead_lettered_at)",
    "CREATE TABLE IF NOT EXISTS bcs_event_delivery_attempts (
        delivery_id TEXT NOT NULL,
        attempt_no INTEGER NOT NULL,
        started_at TEXT NOT NULL,
        completed_at TEXT DEFAULT NULL,
        latency_ms INTEGER DEFAULT NULL,
        result TEXT DEFAULT NULL,
        http_status INTEGER DEFAULT NULL,
        error_category TEXT DEFAULT NULL,
        error_summary TEXT DEFAULT NULL,
        response_bytes_observed INTEGER DEFAULT NULL,
        worker_id TEXT NOT NULL,
        PRIMARY KEY(delivery_id, attempt_no)
    )",
    "CREATE INDEX IF NOT EXISTS idx_event_attempt_result
        ON bcs_event_delivery_attempts(result, started_at)",
    "CREATE TABLE IF NOT EXISTS bcs_event_subscription_audits (
        audit_id TEXT NOT NULL PRIMARY KEY,
        subscription_id TEXT NOT NULL,
        revision INTEGER DEFAULT NULL,
        action TEXT NOT NULL,
        actor_type TEXT NOT NULL,
        actor_id TEXT NOT NULL,
        reason TEXT DEFAULT NULL,
        details_json TEXT DEFAULT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env TEXT NOT NULL
    )",
    "CREATE INDEX IF NOT EXISTS idx_event_audit_subscription
        ON bcs_event_subscription_audits(env, subscription_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_event_audit_actor
        ON bcs_event_subscription_audits(env, actor_type, actor_id, created_at)",
];
