"""Pure public-route inventory for Phase 2 contract-only Space Skills."""

SPACE_SKILL_CONTRACT_ONLY_OPERATIONS = (
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/import-from-git"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/upgrade"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft"),
    ("DELETE", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/files"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/files/{path:path}"),
    ("PUT", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/files/{path:path}"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/replace"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/refresh-from-git"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/grants"),
    ("PUT", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/managers/{manager_user_id}"),
    ("DELETE", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/managers/{manager_user_id}"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/owner-transfer"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/lease"),
    ("PUT", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/lease"),
    ("DELETE", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/lease"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/draft/lease/takeover"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/versions"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/versions/{version}"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/versions/{version}/files"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/versions/{version}/files/{path:path}"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/upgrade-impact"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/publications"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/publications"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/publications/{attempt_id}"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/versions/{version}/materialization-retry"),
    ("GET", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/retirement-impact"),
    ("POST", "/openapi/v1/bots/spaces/{space_id}/skills/{skill_id}/retirement"),
)
