from unittest.mock import MagicMock, patch

import pytest

from secbaas.community.plugins.sandbox.arca.provisioning import (
    AicodingArcaProvisioningStrategy,
)


def _props(theta_key):
    return {"aicoding": {"theta_key": theta_key}}


def test_resolves_aixharness_wire_format():
    secret_plugin = MagicMock()
    secret_plugin.get_kv_secret.return_value = ("unused", "mist-master-key")
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)
    # Generated by aixharness ThetaKeyVault with nonce bytes(range(12)).
    ciphertext = (
        "enc:v1:AAECAwQFBgcICQoLHNRJ-k4pLW8RP9kzemKfjxv0l663ia3nxrQ9dfiD5q9QQTuP"
    )

    assert (
        strategy.resolve_request_api_key(_props(ciphertext)) == "dynamic-arca-api-key"
    )
    secret_plugin.get_kv_secret.assert_called_once_with(
        "other_manual_aixharness_theta_key"
    )


def test_strips_version_prefix_before_decrypt():
    secret_plugin = MagicMock()
    secret_plugin.get_kv_secret.return_value = ("unused", "mist-master-key")
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)

    with patch(
        "secbaas.community.plugins.sandbox.arca.provisioning.aicoding.symmetric_decrypt",
        return_value="dynamic-key",
    ) as decrypt:
        assert (
            strategy.resolve_request_api_key(_props("enc:v1:payload")) == "dynamic-key"
        )

    decrypt.assert_called_once_with("payload", "mist-master-key")


@pytest.mark.parametrize(
    "extra_properties",
    [None, {}, {"other_engine": {}}, {"aicoding": None}, {"aicoding": {}}],
)
def test_unrelated_or_missing_properties_are_ignored(extra_properties):
    secret_plugin = MagicMock()
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)

    assert strategy.resolve_request_api_key(extra_properties) is None
    secret_plugin.get_kv_secret.assert_not_called()


@pytest.mark.parametrize("theta_key", [None, "", "   ", 123])
def test_missing_or_invalid_theta_key_is_ignored(theta_key):
    secret_plugin = MagicMock()
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)

    assert strategy.resolve_request_api_key(_props(theta_key)) is None
    secret_plugin.get_kv_secret.assert_not_called()


def test_unversioned_or_empty_ciphertext_keeps_fixed_credential():
    secret_plugin = MagicMock()
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)

    assert strategy.resolve_request_api_key(_props("historical-plaintext")) is None
    assert strategy.resolve_request_api_key(_props("enc:v1:")) is None
    secret_plugin.get_kv_secret.assert_not_called()


def test_mist_or_decrypt_failure_keeps_fixed_credential():
    secret_plugin = MagicMock()
    secret_plugin.get_kv_secret.side_effect = RuntimeError("mist unavailable")
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)

    assert strategy.resolve_request_api_key(_props("enc:v1:ciphertext")) is None


def test_empty_mist_or_decrypted_value_keeps_fixed_credential():
    secret_plugin = MagicMock()
    strategy = AicodingArcaProvisioningStrategy(secret_plugin)

    secret_plugin.get_kv_secret.return_value = ("unused", "")
    assert strategy.resolve_request_api_key(_props("enc:v1:ciphertext")) is None

    secret_plugin.get_kv_secret.return_value = ("unused", "decrypt-key")
    with patch(
        "secbaas.community.plugins.sandbox.arca.provisioning.aicoding.symmetric_decrypt",
        return_value="   ",
    ):
        assert strategy.resolve_request_api_key(_props("enc:v1:ciphertext")) is None
