"""Stable business error codes for the legacy Skill upload HTTP contract."""

from enum import StrEnum


class SkillUploadErrorCode(StrEnum):
    """Machine-readable failure categories for ``POST /api/skills/upload``."""

    BOT_NOT_FOUND = "SKILL_BOT_NOT_FOUND"
    BOT_OWNER_MISSING = "SKILL_BOT_OWNER_MISSING"
    BOT_NOT_READY = "SKILL_BOT_NOT_READY"
    FILE_PATHS_INVALID = "SKILL_FILE_PATHS_INVALID"
    FILE_PATHS_COUNT_MISMATCH = "SKILL_FILE_PATHS_COUNT_MISMATCH"
    NO_FILES = "SKILL_NO_FILES"
    MANIFEST_MISSING = "SKILL_MANIFEST_MISSING"
    MANIFEST_MULTIPLE = "SKILL_MANIFEST_MULTIPLE"
    MANIFEST_INVALID = "SKILL_MANIFEST_INVALID"
    MANIFEST_ENCODING_INVALID = "SKILL_MANIFEST_ENCODING_INVALID"
    MANIFEST_FIELD_TYPE_INVALID = "SKILL_MANIFEST_FIELD_TYPE_INVALID"
    NAME_TOO_LONG = "SKILL_NAME_TOO_LONG"
    DESCRIPTION_EMPTY = "SKILL_DESCRIPTION_EMPTY"
    DESCRIPTION_TOO_LONG = "SKILL_DESCRIPTION_TOO_LONG"
    FILE_OUTSIDE_ROOT = "SKILL_FILE_OUTSIDE_ROOT"
    PATH_INVALID = "SKILL_PATH_INVALID"
    NAME_MISSING = "SKILL_NAME_MISSING"
    NAME_EMPTY = "SKILL_NAME_EMPTY"
    DESCRIPTION_MISSING = "SKILL_DESCRIPTION_MISSING"
    ROOT_NAME_MISMATCH = "SKILL_ROOT_NAME_MISMATCH"
    NAME_INVALID = "SKILL_NAME_INVALID"
    NAME_RESERVED = "SKILL_NAME_RESERVED"
    ZIP_INVALID = "SKILL_ZIP_INVALID"
    RUNTIME_UNAVAILABLE = "SKILL_RUNTIME_UNAVAILABLE"
    UPLOAD_FAILED = "SKILL_UPLOAD_FAILED"
